(function(root){
 'use strict';
 const Core=typeof module!=='undefined'&&module.exports?require('./sync-core.js'):root.SyncCore;
 const KEYS={quizAnswers:'english-notes.quiz.answers.v1',settings:'english-notes.quiz.settings.v1',bookmarks:'english-notes.quiz.bookmarks.v1',unsaved:'english-notes.app.unsaved-custom-words.v1',goals:'english-notes.app.goals.v1',sessions:'english-notes.app.unit-sessions.v1',lastUnit:'english-notes.app.last-unit.v1',articleSaves:'english-notes.app.article-saves.v1',customWords:'english-notes.app.custom-words.v1',reads:'english-notes.article.read.v1',opinions:'english-notes.article.opinion.v1',articleAnswers:'english-notes.article.answers.v1'};
 const emptyRows=()=>Object.fromEntries(Core.TABLES.map(t=>[t,{}]));
 const fresh=()=>({formatVersion:1,values:{},rows:emptyRows(),outbox:emptyRows(),cursors:{},migration:{snapshotId:Core.uuid(),importedSnapshots:{}}});
 const parse=(state,key,fallback)=>state.values[key]===undefined?fallback:JSON.parse(state.values[key]);
 const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
 const cleanRow=row=>{const next=Core.clone(row);delete next.user_id;return next;};
 const savedKeys=[KEYS.bookmarks,KEYS.articleSaves,KEYS.customWords,KEYS.unsaved];
 class StorageAdapter {
  constructor(storage,options={}){this.storage=storage;this.userId=options.userId||null;this.catalog=[];this.legacyWords=[];this.listeners=new Set();this.now=options.now||(()=>new Date().toISOString());this.draft=null;this.changed=null;this.state=this.load(this.userId);}
  namespace(uid=this.userId){if(uid!==null&&!/^[a-zA-Z0-9_-]+$/.test(uid))throw Error('Invalid user identifier');return uid===null?'english-notes.guest.state.v1':`english-notes.user.${uid}.state.v1`;}
  load(uid){const raw=this.storage.getItem(this.namespace(uid));if(raw!==null){const state=JSON.parse(raw);if(state.formatVersion!==1||!state.values||!state.rows||!state.outbox)throw Error('Invalid local storage envelope');for(const table of Core.TABLES){state.rows[table]??={};state.outbox[table]??={};}state.cursors??={};state.migration??={snapshotId:Core.uuid(),importedSnapshots:{}};return state;}
   const state=fresh();if(uid===null){for(const key of Object.values(KEYS)){const value=this.storage.getItem(key);if(value!==null)state.values[key]=value;}if(Object.keys(state.values).length){state.migration.copiedAt=this.now();this.reconcile(state,fresh(),new Set(Object.keys(state.values)));state.migration.legacyValues=Core.clone(state.values);}}
   this.storage.setItem(this.namespace(uid),JSON.stringify(state));return state;
  }
  notify(reason,extra={}){const event={reason,userId:this.userId,...extra};for(const fn of this.listeners)try{fn(event)}catch(error){if(root.console?.error)root.console.error('Storage subscriber failed',error)}}
  subscribe(fn){this.listeners.add(fn);return ()=>this.listeners.delete(fn)}
  getUser(){return this.userId}
  setUser(uid){uid=uid??null;if(uid===this.userId)return;const state=this.load(uid);this.userId=uid;this.state=state;this.notify('user')}
  getItem(key){const state=this.draft||this.state;return Object.prototype.hasOwnProperty.call(state.values,key)?state.values[key]:null}
  setItem(key,value){if(typeof key!=='string'||!key.startsWith('english-notes.'))throw Error('Invalid learning storage key');if(this.draft){this.draft.values[key]=String(value);this.changed.add(key);return;}return this.transaction(()=>this.setItem(key,value))}
  removeItem(key){if(this.draft){delete this.draft.values[key];this.changed.add(key);return;}return this.transaction(()=>this.removeItem(key))}
  transaction(fn){if(this.draft)return fn(this);const draft=Core.clone(this.state);this.draft=draft;this.changed=new Set();let value;try{value=fn(this);if(value?.then)throw Error('Storage transactions must be synchronous');if(this.changed.size){this.reconcile(draft,this.state,this.changed);if(this.userId===null)draft.migration.snapshotId=Core.uuid();this.storage.setItem(this.namespace(),JSON.stringify(draft));this.state=draft;}}finally{this.draft=null;this.changed=null;}if(value!==undefined||this.state===draft)this.notify('write');return value}
  commit(draft,reason,extra={}){this.storage.setItem(this.namespace(),JSON.stringify(draft));this.state=draft;this.notify(reason,extra)}
  putLocal(state,table,row){Core.validateRow(table,row);const key=Core.rowKey(table,row),old=state.rows[table][key];const comparable=x=>{if(!x)return x;const v=Core.clone(x);delete v.updated_at;delete v.server_updated_at;return v;};if(old&&same(comparable(old),comparable(row)))return;if(old&&Core.isAppendOnly(table))return;state.rows[table][key]=cleanRow(row);state.outbox[table][key]={revision:Core.uuid(),row:cleanRow(row)};}
  reconcile(state,previous,changed){const now=this.now(),affected=new Set();
   if(changed.has(KEYS.quizAnswers)||changed.has(KEYS.articleAnswers)){
    for(const [logical,kind] of [[KEYS.quizAnswers,'vocabulary'],[KEYS.articleAnswers,'comprehension']]){if(!changed.has(logical))continue;const raw=parse(state,logical,kind==='vocabulary'?[]:{}),events=kind==='vocabulary'?raw:Object.values(raw);if(!Array.isArray(events))throw Error('Invalid answer collection');const normalized=[];for(const event of events){const row=Core.answerRow(event,kind);Core.validateRow('answer_logs',row);this.putLocal(state,'answer_logs',row);normalized.push(Core.answerEvent(state.rows.answer_logs[row.event_id]));}state.values[logical]=JSON.stringify(kind==='vocabulary'?Core.sortAnswers(normalized):Object.fromEntries(normalized.map(e=>[e.eventId,e])));}
    affected.add('answer_logs');
   }
   if(changed.has(KEYS.settings)||changed.has(KEYS.goals)){
    for(const [logical,allowed,defaults] of [[KEYS.settings,['mode','autoAdvance'],{mode:'ja',autoAdvance:true}],[KEYS.goals,['daily','weekly'],{daily:null,weekly:null}]]){if(!changed.has(logical))continue;const value=parse(state,logical,{}),old=parse(previous,logical,{});if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid preferences');for(const key of allowed){if(!Object.hasOwn(value,key)&&!state.rows.preferences[key])continue;const next=Object.hasOwn(value,key)?value[key]:defaults[key];if(!Core.validPreference(key,next))throw Error('Invalid preference');if(!same(next,old[key])||!state.rows.preferences[key])this.putLocal(state,'preferences',{setting_key:key,value:next,updated_at:now});}}
    affected.add('preferences');
   }
   if(savedKeys.some(key=>changed.has(key))){
    const bookmarks=parse(state,KEYS.bookmarks,[]),indexes=parse(state,KEYS.articleSaves,[]),custom=parse(state,KEYS.customWords,[]),unsaved=new Set(parse(state,KEYS.unsaved,[]).map(Core.normalize));if(!Array.isArray(bookmarks)||!Array.isArray(indexes)||!Array.isArray(custom))throw Error('Invalid saved words');const desired=new Map();
    const add=(word,origin)=>{if(!word)return;const wordKey=Core.normalize(word.headword??word.en);if(!wordKey)return;const item=this.catalog.find(x=>Core.normalize(x.headword)===wordKey),id=item?.id??word.catalog_word_id??null;const payload=origin==='custom'?{...word,origin:'custom'}:{headword:item?.headword||word.headword||word.en,meaning:item?.meaning||word.meaning||word.ja||'',definition:item?.definition||word.definition||word.def||'',example:item?.example||word.example||'',origin:'catalog'};desired.set(wordKey,{word_key:wordKey,catalog_word_id:id,payload,saved:true,deleted_at:null,updated_at:now});};
    for(const id of bookmarks){const item=this.catalog.find(w=>w.id===id);if(item)add(item,'catalog');else{const old=Object.values(state.rows.saved_words).find(w=>w.catalog_word_id===id);if(old)desired.set(old.word_key,{...old,saved:true,deleted_at:null,updated_at:now});}}
    for(const index of indexes)add(this.legacyWords[index],'catalog');for(const word of custom)if(!unsaved.has(Core.normalize(word.headword??word.en)))add(word,'custom');
    for(const [key,row] of desired)this.putLocal(state,'saved_words',row);for(const [key,row] of Object.entries(state.rows.saved_words))if(row.saved&&!desired.has(key))this.putLocal(state,'saved_words',{...row,saved:false,deleted_at:now,updated_at:now});affected.add('saved_words');
   }
   if(changed.has(KEYS.sessions)){const values=parse(state,KEYS.sessions,[]);if(!Array.isArray(values))throw Error('Invalid unit sessions');for(const s of values)this.putLocal(state,'unit_sessions',{session_id:s.sessionId,unit_id:s.unitId,mode:s.mode,total:s.total,correct:s.correct,completed_at:s.completedAt});affected.add('unit_sessions');}
   if(changed.has(KEYS.reads)){const values=parse(state,KEYS.reads,{}),keys=new Set([...Object.keys(values),...Object.keys(state.rows.article_states)]);for(const articleId of keys){const v=values[articleId],read=!!v?.completedAt;const old=state.rows.article_states[articleId];if(!old||old.read!==read||old.read_at!==(v?.completedAt||null))this.putLocal(state,'article_states',{article_id:articleId,read,read_at:v?.completedAt||null,updated_at:now});}affected.add('article_states');}
   if(changed.has(KEYS.opinions)){const values=parse(state,KEYS.opinions,{}),ids=new Set([...Object.keys(values),...Object.values(state.rows.opinion_drafts).map(x=>x.article_id)]);for(const articleId of ids){const v=values[articleId],body=String(v?.text??''),row={article_id:articleId,prompt_id:v?.promptId||'opinion-1',body,updated_at:v?.updatedAt||now,deleted_at:body?null:now};this.putLocal(state,'opinion_drafts',row);}affected.add('opinion_drafts');}
   this.refreshValues(state,affected);
  }
  refreshValues(state,tables){
   if(tables.has('answer_logs')){const events=Core.sortAnswers(Object.values(state.rows.answer_logs).map(Core.answerEvent));state.values[KEYS.quizAnswers]=JSON.stringify(events.filter(e=>e.kind==='vocabulary'));state.values[KEYS.articleAnswers]=JSON.stringify(Object.fromEntries(events.filter(e=>e.kind==='comprehension').map(e=>[e.eventId,e])));}
   if(tables.has('preferences')){const settings={mode:'ja',autoAdvance:true,...parse(state,KEYS.settings,{})},goals={daily:null,weekly:null,...parse(state,KEYS.goals,{})};for(const row of Object.values(state.rows.preferences)){if(['mode','autoAdvance'].includes(row.setting_key))settings[row.setting_key]=row.value;else goals[row.setting_key]=row.value;}state.values[KEYS.settings]=JSON.stringify(settings);state.values[KEYS.goals]=JSON.stringify(goals);}
   if(tables.has('saved_words')){
    const rows=Object.values(state.rows.saved_words),unresolved=parse(state,KEYS.bookmarks,[]).filter(id=>!this.catalog.some(x=>x.id===id)&&!rows.some(r=>r.catalog_word_id===id));state.values[KEYS.bookmarks]=JSON.stringify([...new Set([...unresolved,...rows.filter(r=>r.saved&&r.catalog_word_id).map(r=>r.catalog_word_id)])]);const unresolvedIndexes=parse(state,KEYS.articleSaves,[]).filter(index=>!this.legacyWords[index]);state.values[KEYS.articleSaves]=JSON.stringify([...new Set([...unresolvedIndexes,...this.legacyWords.map((w,i)=>({w,i})).filter(({w})=>rows.some(r=>r.word_key===Core.normalize(w.headword??w.en)&&r.saved)).map(x=>x.i)])]);
    const custom=rows.filter(r=>!r.catalog_word_id||r.payload?.origin==='custom').map(r=>({...r.payload,en:r.payload.en??r.payload.headword??r.word_key,ja:r.payload.ja??r.payload.meaning??'',def:r.payload.def??r.payload.definition??'',example:r.payload.example||''}));state.values[KEYS.customWords]=JSON.stringify(custom);state.values[KEYS.unsaved]=JSON.stringify(rows.filter(r=>!r.saved).map(r=>r.word_key));
   }
   if(tables.has('unit_sessions'))state.values[KEYS.sessions]=JSON.stringify(Object.values(state.rows.unit_sessions).sort((a,b)=>a.completed_at.localeCompare(b.completed_at)||a.session_id.localeCompare(b.session_id)).map(s=>({sessionId:s.session_id,unitId:s.unit_id,mode:s.mode,total:s.total,correct:s.correct,completedAt:s.completed_at})));
   if(tables.has('article_states')){const old=parse(state,KEYS.reads,{}),values={};for(const r of Object.values(state.rows.article_states))values[r.article_id]={...(old[r.article_id]||{}),articleId:r.article_id,completedAt:r.read?r.read_at:null};state.values[KEYS.reads]=JSON.stringify(values);}
   if(tables.has('opinion_drafts')){const old=parse(state,KEYS.opinions,{}),values={};for(const r of Object.values(state.rows.opinion_drafts))values[r.article_id]={...(old[r.article_id]||{}),articleId:r.article_id,promptId:r.prompt_id,text:r.deleted_at?'':r.body,updatedAt:r.updated_at};state.values[KEYS.opinions]=JSON.stringify(values);}
  }
  setCatalog(items,legacyWords=[]){this.catalog=[...items];this.legacyWords=[...legacyWords];const draft=Core.clone(this.state);this.reconcile(draft,this.state,new Set(savedKeys));if(!same(draft,this.state))this.commit(draft,'catalog');}
  snapshot(){return Core.clone(this.state)}
  pending(){return Core.TABLES.flatMap(table=>Object.entries(this.state.outbox[table]).map(([key,p])=>({table,key,revision:p.revision,row:{...Core.clone(p.row),...(this.userId?{user_id:this.userId}:{})}})))}
  acknowledge(table,key,revision){if(this.state.outbox[table]?.[key]?.revision!==revision)return false;const draft=Core.clone(this.state);delete draft.outbox[table][key];this.commit(draft,'ack');return true}
  merge(table,rows){if(!Core.TABLES.includes(table)||!Array.isArray(rows))throw Error('Invalid remote collection');const draft=Core.clone(this.state);let changed=false;for(const incoming of rows){if(incoming.user_id&&incoming.user_id!==this.userId)throw Error('Remote user mismatch');const row=cleanRow(incoming);Core.validateRow(table,row);const key=Core.rowKey(table,row),old=draft.rows[table][key];if(draft.outbox[table][key])continue;if(old&&Core.isAppendOnly(table))continue;if(old&&!Core.isAppendOnly(table)&&Core.compareTime(row.updated_at,old.updated_at)<0)continue;if(!same(old,row)){draft.rows[table][key]=row;changed=true;}}
   if(changed){this.refreshValues(draft,new Set([table]));this.commit(draft,'merge',{table});}return changed;
  }
  cursor(table,value){if(!Core.TABLES.includes(table))throw Error('Unknown sync table');if(arguments.length===1)return this.state.cursors[table]??null;if(value!==null&&!Number.isFinite(Date.parse(value)))throw Error('Invalid sync cursor');const draft=Core.clone(this.state);if(value===null)delete draft.cursors[table];else draft.cursors[table]=value;this.commit(draft,'cursor');return value}
  getCursor(table){return this.cursor(table)}
  setCursor(table,value){return this.cursor(table,value)}
  guestState(){return this.userId===null?Core.clone(this.state):this.load(null)}
  legacyKeys(guest){if(!guest.migration.legacyValues)return emptyRows();const draft=fresh();draft.values=Core.clone(guest.migration.legacyValues);this.reconcile(draft,fresh(),new Set(Object.keys(draft.values)));return draft.rows;}
  migrationPreview(){const guest=this.guestState(),legacy=this.legacyKeys(guest),counts={},guestCounts={},legacyCounts={},tables={};for(const table of Core.TABLES){tables[table]=Object.keys(guest.rows[table]);counts[table]=tables[table].length;legacyCounts[table]=tables[table].filter(key=>Object.hasOwn(legacy[table],key)).length;guestCounts[table]=counts[table]-legacyCounts[table];}const total=Object.values(counts).reduce((a,b)=>a+b,0),snapshotId=guest.migration.snapshotId,alreadyImported=!!guest.migration.importedSnapshots?.[snapshotId];return {available:total>0&&!alreadyImported,alreadyImported,snapshotId,counts,guestCounts,legacyCounts,total,tables};}
  importGuest(){if(!this.userId)throw Error('Login required before importing guest data');const guest=this.guestState(),preview=this.migrationPreview();if(preview.alreadyImported)return {...preview,imported:false,targetRows:{}};const draft=Core.clone(this.state),targetRows={};for(const table of Core.TABLES){targetRows[table]=[];for(const [key,row] of Object.entries(guest.rows[table])){const old=draft.rows[table][key];if(!old||!Core.isAppendOnly(table)&&Core.compareTime(row.updated_at,old.updated_at)>0)this.putLocal(draft,table,row);targetRows[table].push(Core.clone(draft.rows[table][key]));}}
   draft.migration.pendingGuestImport={snapshotId:preview.snapshotId,userId:this.userId,tables:preview.tables};this.refreshValues(draft,new Set(Core.TABLES));this.commit(draft,'import');return {...preview,imported:true,targetRows};
  }
  markGuestImported(snapshotId,userId=this.userId){if(!this.userId||userId!==this.userId)throw Error('Import account mismatch');const guest=this.guestState();if(guest.migration.snapshotId!==snapshotId)throw Error('Guest data changed during migration');guest.migration.importedSnapshots??={};guest.migration.importedSnapshots[snapshotId]={userId,completedAt:this.now()};this.storage.setItem(this.namespace(null),JSON.stringify(guest));const draft=Core.clone(this.state);delete draft.migration.pendingGuestImport;this.commit(draft,'import');return true}
  exportData(scope){const userId=scope==='guest'?null:this.userId,state=scope==='guest'?this.guestState():this.state;return {formatVersion:1,exportedAt:this.now(),userId,learningData:{values:Core.clone(state.values),rows:Core.clone(state.rows)},pendingData:Core.TABLES.flatMap(table=>Object.entries(state.outbox[table]).map(([key,p])=>({table,key,revision:p.revision,row:Core.clone(p.row)}))),cursors:Core.clone(state.cursors),migration:Core.clone(state.migration)};}
 }
 const createStorage=(storage,options)=>new StorageAdapter(storage,options);
 const api={createStorage,StorageAdapter,KEYS};
 if(typeof module!=='undefined'&&module.exports)module.exports=api;else {root.AppStorageFactory=api;try{root.AppStorage=createStorage(root.localStorage)}catch(error){root.AppStorageError=error;}}
})(typeof window!=='undefined'?window:globalThis);
