(function(root){
 'use strict';
 const categories={work:'仕事',knowledge:'教養',culture:'日常・文化',health:'健康・ライフスタイル'},levels=['A2','B1','B2','C1'],names={A2:'初級',B1:'中級',B2:'中上級',C1:'上級'};
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function route(href){const p=new URL(href).searchParams;return {category:categories[p.get('category')]?p.get('category'):'',level:levels.includes(p.get('level'))?p.get('level'):'',q:(p.get('q')||'').trim(),list:p.get('view')==='list'};}
 function url(href,value={}){const u=new URL(href);for(const key of ['category','level','q','view'])u.searchParams.delete(key);if(categories[value.category])u.searchParams.set('category',value.category);if(levels.includes(value.level))u.searchParams.set('level',value.level);if(value.q?.trim())u.searchParams.set('q',value.q.trim());u.searchParams.set('view',value.list?'list':'articles');return u.href;}
 function select(rows,filters={}){const q=(filters.q||'').trim().toLocaleLowerCase();return rows.filter(a=>(!filters.category||a.category===categories[filters.category])&&(!filters.level||a.level===filters.level)&&(!q||(a.searchText||[a.title,a.summaryJa,a.category].join(' ')).toLocaleLowerCase().includes(q))).sort((a,b)=>Date.parse(b.sourcePublishedAt)-Date.parse(a.sourcePublishedAt)||Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)||a.id.localeCompare(b.id));}
 function age(date,now=new Date()){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);return Math.floor((Date.parse(today+'T00:00:00Z')-Date.parse(String(date).slice(0,10)+'T00:00:00Z'))/86400000);}
 const isNew=(a,now)=>age(a.sourcePublishedAt,now)>=0&&age(a.sourcePublishedAt,now)<=7;
 const dateLabel=a=>{const d=new Date(a.sourcePublishedAt);return Number.isFinite(d.getTime())?'元記事 '+new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric',timeZone:'UTC'}).format(d):'';};
 const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>';
 const tagIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M3 3h8l10 10-8 8L3 11Z"/><circle cx="7.5" cy="7.5" r="1"/></svg>';
 function toolbar(f,searchOpen){const options=(items,current)=>Object.entries(items).map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('');return `<div class="ab-toolbar"><div class="ab-title"><h1>記事</h1><button data-ab-top class="ab-text ab-top">トップ</button></div><label class="ab-category"><span class="ab-desktop">分野</span><select data-ab-category aria-label="分野">${options({'':'すべて',...categories},f.category||'')}</select></label><button class="ab-search-toggle" data-ab-search-toggle aria-label="記事を検索" aria-expanded="${!!searchOpen}" aria-controls="ab-search">${icon}</button><label class="ab-search ${searchOpen?'is-open':''}" id="ab-search">${icon}<input type="search" name="q" data-ab-search aria-label="キーワード検索" placeholder="キーワード検索" value="${esc(f.q||'')}" autocomplete="off"></label><label class="ab-level-select"><span class="ab-desktop">レベル</span><select data-ab-level aria-label="レベル">${options({'':'すべて',A2:'A2',B1:'B1',B2:'B2',C1:'C1'},f.level||'')}</select></label></div>`;}
 function photo(a){return a.photo?.assetPath&&/^assets\/[a-zA-Z0-9_./-]+$/.test(a.photo.assetPath)?`<img src="${esc(a.photo.assetPath)}" alt="${esc(a.photo.alt||'')}" loading="lazy">`:`<div class="ab-photo-fallback" aria-hidden="true">${tagIcon}</div>`;}
 function card(a,kind,options){const tile=kind==='tile'||kind==='lead',check=!tile&&options.isRead?.(a)?'<span class="ab-read" aria-label="読了">✓</span>':'';return `<article class="ab-card ab-${kind}" role="link" tabindex="0" data-a5-open="${esc(a.id)}" aria-label="${esc(a.title)}"><div class="ab-photo">${photo(a)}</div>${tile&&isNew(a,options.now)?'<span class="ab-new">NEW</span>':''}<div class="ab-copy"><h2>${esc(a.title)} ${check}</h2>${tile?`<div class="ab-tile-meta"><span class="ab-tile-level"><span class="ab-level">${esc(a.level)}</span> ${esc(names[a.level]||'')}</span><span class="ab-category-tag">${esc(a.category)}</span></div>`:kind==='past'?`<div class="ab-meta"><span class="ab-level">${esc(a.level)}</span><span>${esc(dateLabel(a))}</span></div>`:`${kind==='result'?`<p class="ab-summary">${esc(a.summaryJa)}</p>`:''}<div class="ab-meta"><span class="ab-level">${esc(a.level)}</span>${kind==='result'?`<span>${esc(a.category)}</span>`:''}<span>約${esc(a.readingMinutes)}分</span><span>${esc(dateLabel(a))}</span></div>`}</div></article>`;}
 function render(rows,f={},options={}){const all=select(rows),entries=select(rows,f),filtered=Boolean(f.category||f.level||f.q?.trim()||f.list);let content='';if(filtered||all.length<5){const description=[f.level,categories[f.category],f.q?`「${f.q}」`:null].filter(Boolean).join('・');content=entries.length?`<div class="ab-result-head"><p role="status">${esc(description?description+'の記事':'記事')} ${entries.length}件</p>${filtered?'<button class="ab-text" data-ab-top>条件をクリア</button>':''}</div><div class="ab-results-grid">${entries.map(a=>card(a,'result',options)).join('')}</div>`:`<div class="ab-empty"><p role="status">条件に合う記事がありません</p><button class="ab-text" data-ab-top>条件をクリア</button></div>`;}else{const head=all.slice(0,5),past=all.filter(a=>age(a.sourcePublishedAt,options.now)>=15);content=`<section class="ab-mosaic" aria-label="注目の記事">${card(head[0],'lead',options)}<div class="ab-tiles">${head.slice(1).map(a=>card(a,'tile',options)).join('')}</div></section><div class="ab-all-link"><button class="ab-text" data-ab-all>一覧を見る ›</button></div><div class="ab-lower ${past.length?'has-past':''}"><div class="ab-shelves">${Object.entries(categories).map(([key,label])=>{const shelf=all.filter(a=>a.category===label).slice(0,3);return shelf.length?`<section class="ab-shelf-section"><div class="ab-section-head"><h2>${tagIcon}${esc(label)}</h2><button class="ab-text" data-ab-shelf="${key}">一覧を見る ›</button></div><div class="ab-shelf-grid">${shelf.map(a=>card(a,'shelf',options)).join('')}</div></section>`:''}).join('')}</div>${past.length?`<aside class="ab-past"><h2>過去の記事</h2>${past.map(a=>card(a,'past',options)).join('')}</aside>`:''}</div>`;}return `<div class="ab-browser">${toolbar(f,options.searchOpen)}${content}</div>`;}
 const api={route,url,select,age,isNew,render,categories};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ArticleBrowse=api;
})(typeof window!=='undefined'?window:globalThis);
