const icons={home:'M3 10 12 3l9 7v10H3z M9 20v-7h6v7',vocab:'M5 3h14v18H5z M8 8h8 M8 12h6 M8 16h4',articles:'M12 5v16 M12 5C8 2 3 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-4-2-7-1-10 1',listen:'M5 10v4 M9 6v12 M13 3v18 M17 6v12 M21 10v4',records:'M4 20V10 M10 20V4 M16 20v-7 M22 20V7',arrow:'m9 5 7 7-7 7'};
const ico=n=>`<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.arrow}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manualMinutes=0,quizQueue=[0,1,2],quizPosition=0;
let view='home',filter='すべて',wordFilter='すべて',selectedWord=0,selectedArticle=0,mode='日本語',chosen=null,listeningMode='自由練習',playing=false;
const words=[{en:'compelling',ja:'説得力のある',def:'convincing',example:'She made a compelling case for the proposal.',status:'復習予定'},{en:'underlying assumptions',ja:'根底にある前提',def:'basic beliefs taken for granted',example:'We need to examine the underlying assumptions.',status:'復習予定'},{en:'on the fence',ja:'決めかねている',def:'undecided',example:'I’m still on the fence about the offer.',status:'復習予定'},{en:'trade-off',ja:'両立しない利点と欠点',def:'a balance between competing benefits',example:'Every decision involves a trade-off.',status:'定着'},{en:'ramifications',ja:'派生する影響',def:'consequences',example:'Consider the ramifications of this decision.',status:'学習中'}];
const lessons=[{title:'Making a compelling case',jp:'説得力のある意見を伝える',genre:'仕事',cover:'Make<br>a case.',style:'',word:0,text:['A compelling argument gives people a strong reason to agree. When you make a case for a proposal, explain why it matters and support your ideas with evidence.','Compare “It is a good idea” with “There is a compelling reason to change our approach.” The second sentence signals that the reason deserves serious attention.'],source:'Cambridge Dictionary — compelling',url:'https://dictionary.cambridge.org/dictionary/english/compelling'},{title:'Looking beneath the surface',jp:'前提に目を向ける',genre:'教養',cover:'Beneath<br>the surface.',style:'two',word:1,text:['An underlying idea or condition exists beneath what is immediately visible. An assumption is something we accept as true without proof.','When reading an argument, ask: what are the underlying assumptions? This question helps you distinguish what is stated from what is taken for granted.'],source:'Cambridge Dictionary — underlying / assumption',url:'https://dictionary.cambridge.org/dictionary/english/underlying',extra:'https://dictionary.cambridge.org/dictionary/english/assumption'},{title:'When you’re on the fence',jp:'迷っている気持ちを伝える',genre:'日常・文化',cover:'Still<br>deciding.',style:'three',word:2,text:['If you are on the fence, you have not decided which side to support or which option to choose. The expression is useful when you want to describe uncertainty.','“I’m on the fence about the invitation” tells the listener that you are still considering your decision. You can follow it with the reasons for your hesitation.'],source:'Cambridge Dictionary — on the fence',url:'https://dictionary.cambridge.org/dictionary/english/on-the-fence'}];
const nav=[['home','ホーム'],['vocab','単語・表現'],['articles','記事'],['listen','リスニング'],['records','学習記録']];
function cover(l,i,extra=''){return `<div class="cover ${l.style} ${extra}" aria-hidden="true"><span class="number">ENGLISH NOTES / 0${i+1}</span><strong>${l.cover}</strong></div>`}
function go(v){if(playing)stopAudio();view=v;chosen=null;render();window.scrollTo(0,0)}
function lessonOpen(i){selectedArticle=i;go('article')}
function wordOpen(i){selectedWord=i;go('word')}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.hidden=true,2500)}
function weekdays(){return `<div class="weekdays">${['月','火','水','木','金','土','日'].map((d,i)=>`<div class="day ${i<6?'done':''} ${i===5?'today':''}">${d}<i>${i<6?'✓':'·'}</i></div>`).join('')}</div>`}
function home(){return `<div class="welcome"><div><div class="eyebrow">10月3日 土曜日</div><h1>今日も、英語をひとつ。</h1></div><span class="streakchip">6日連続</span></div><section class="spotlight"><div class="eyebrow">TODAY’S PRACTICE</div><h2>覚えた言葉を、<br>使える言葉に。</h2><p>${words.some(w=>w.status==='復習予定')?'今日は'+words.filter(w=>w.status==='復習予定').length+'つの表現を復習しましょう。':'今日の復習は完了。新しい表現に出会いましょう。'}</p><span class="symbol" aria-hidden="true">Aa</span><button onclick="startReview()">復習をはじめる <span>→</span></button></section><div class="progressline"><span>今週の目標</span><div class="track" aria-label="今週の学習目標${Math.round((90+manualMinutes)/120*100)}%達成"><i style="width:${Math.min(100,(90+manualMinutes)/120*100)}%"></i></div><b>${90+manualMinutes} / 120分</b></div><div class="shortcuts"><button class="shortcut" onclick="go('articles')">${ico('articles')}<span><b>記事を読む</b><small>気になるテーマから</small></span></button><button class="shortcut" onclick="go('listen')">${ico('listen')}<span><b>耳で学ぶ</b><small>英語のリズムに触れる</small></span></button></div><section class="section"><div class="sectionhead"><h2>今週の読みもの</h2><button class="textbtn" onclick="go('articles')">すべて見る →</button></div><div class="shelf">${lessons.map((l,i)=>`<button class="lesson" onclick="lessonOpen(${i})">${cover(l,i)}<div class="meta">${l.genre} · B2–C1 · 表現解説</div><h3>${l.title}</h3><p>${l.jp}</p></button>`).join('')}</div></section><section class="section"><div class="sectionhead"><h2>続けている、あなたへ。</h2><button class="textbtn" onclick="go('records')">記録を見る →</button></div>${weekdays()}</section>`}
function vocabulary(){const items=words.map((w,i)=>({w,i})).filter(({w})=>wordFilter==='すべて'||w.status===wordFilter);return `<div class="eyebrow">YOUR WORDS</div><div class="sectionhead"><h1>単語・表現</h1><button class="textbtn" onclick="addWord()">＋ 追加</button></div><p class="muted">出会った言葉を、自分のものに。</p><div class="tabs">${['すべて','復習予定','定着'].map(t=>`<button class="${wordFilter===t?'active':''}" onclick="wordFilter='${t}';render()">${t}${t==='すべて'?` ${words.length}`:''}</button>`).join('')}</div><div class="wordlist">${items.map(({w,i})=>`<button class="wordcard" onclick="wordOpen(${i})"><span><strong>${esc(w.en)}</strong><p>${esc(w.ja)}</p></span><span class="status">${esc(w.status)}</span></button>`).join('')||'<p class="empty">ここに覚えた言葉が増えていきます。</p>'}</div><div class="section"><button class="primary full" onclick="startReview()">復習をはじめる →</button></div>`}
function wordDetail(){const w=words[selectedWord];return `<button class="back" onclick="go('vocab')">← 単語・表現</button><div class="eyebrow">${esc(w.status)}</div><div class="flash"><strong>${esc(w.en)}</strong><p>${esc(w.ja)}</p></div><div class="wordmeaning"><h3>${esc(w.def)}</h3><p>${esc(w.example)}</p></div><button class="primary full" onclick="startReview(selectedWord)">この表現を練習する →</button><button class="textbtn full" onclick="words[selectedWord].status='定着';render();toast('定着した表現に移しました')">覚えた表現にする</button>`}
function quiz(){const w=words[selectedWord], correct=mode==='日本語'?w.ja:w.def, alternatives=(mode==='日本語'?['慎重な','曖昧な','一時的な','正確な','独立した','穏やかな']:['cautious','ambiguous','temporary','precise','independent','calm']).filter(a=>a.trim().toLowerCase()!==correct.trim().toLowerCase()).slice(0,3);const correctIndex=selectedWord%4,answers=[...alternatives];answers.splice(correctIndex,0,correct);return `<button class="back" onclick="go('vocab')">← 単語・表現</button><div class="sectionhead"><h2>言葉を思い出す</h2><span class="muted">${quizPosition+1} / ${quizQueue.length}</span></div><div class="tabs">${['日本語','英語'].map(m=>`<button class="${mode===m?'active':''}" onclick="mode='${m}';chosen=null;render()" ${m==='英語'&&!w.def?'disabled title="英語の意味が登録されている表現で利用できます"':''}>${m}で答える</button>`).join('')}</div><div class="flash"><strong>${esc(w.en)}</strong><p>いちばん近い意味を選んでください</p></div><div class="choices">${answers.map((a,i)=>`<button class="choice ${chosen!==null?(i===correctIndex?'correct':i===chosen?'wrong':''):''}" onclick="answer(${i})" ${chosen!==null?'disabled':''}><b>${String.fromCharCode(65+i)}</b>${esc(a)}</button>`).join('')}</div>${chosen!==null?`<div class="feedback" role="status">${chosen===correctIndex?'正解です。':'正解は '+esc(correct)+' です。'}</div><p class="muted">${esc(w.example)}</p><button class="primary full" onclick="nextWord()">${quizPosition<quizQueue.length-1?'次の表現へ →':'復習を終える ✓'}</button>`:''}`}
function startReview(i){quizQueue=Number.isInteger(i)?[i]:words.map((w,i)=>({w,i})).filter(({w})=>w.status==='復習予定').map(({i})=>i);if(!quizQueue.length){toast('今日の復習は終わりました');return}quizPosition=0;selectedWord=quizQueue[0];if(!words[selectedWord].def)mode='日本語';go('quiz')}
function answer(i){chosen=i;render()}function nextWord(){if(quizPosition<quizQueue.length-1){quizPosition++;selectedWord=quizQueue[quizPosition];chosen=null;render()}else{go('vocab');toast('復習が終わりました。おつかれさま！')}}
function articles(){return `<div class="eyebrow">READ & DISCOVER</div><h1>英語で、世界を広げる。</h1><p class="muted">興味のあるテーマが、学びの入口。</p><div class="filters">${['すべて','仕事','教養','日常・文化'].map(f=>`<button class="${filter===f?'active':''}" onclick="filter='${f}';render()">${f}</button>`).join('')}</div><div class="articlelist">${lessons.map((l,i)=>({l,i})).filter(({l})=>filter==='すべて'||l.genre===filter).map(({l,i})=>`<button class="articleitem" onclick="lessonOpen(${i})">${cover(l,i)}<span><div class="meta">${l.genre} · B2–C1 · 表現解説</div><h3>${l.title}</h3><p>${l.jp}</p></span></button>`).join('')}</div>`}
function article(){const l=lessons[selectedArticle];return `<button class="back" onclick="go('articles')">← 記事</button><div class="eyebrow">${l.genre} · B2–C1</div><h1>${l.title}</h1><p class="muted">${l.jp}</p>${cover(l,selectedArticle,'detailcover')}<div class="articlebody">${l.text.map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="wordmeaning"><div class="sectionhead"><h3>${esc(words[l.word].en)}</h3><button class="textbtn" onclick="saveArticleWord()">${words[l.word].bookmarked?'保存済み ✓':'保存する ＋'}</button></div><p>${esc(words[l.word].ja)}</p></div><button class="primary full" onclick="go('listen')">この英文を聴く →</button><div class="source">出典・参考資料<br><a href="${l.url}" target="_blank" rel="noopener noreferrer">${l.source} ↗</a>${l.extra?`<br><a href="${l.extra}" target="_blank" rel="noopener noreferrer">Cambridge Dictionary — assumption ↗</a>`:''}<p>辞書の語義に基づく表現解説。英文・構成：English Notes</p></div>`}
function saveArticleWord(){words[lessons[selectedArticle].word].bookmarked=true;render();toast('単語・表現に保存しました')}
function listening(){const l=lessons[selectedArticle];return `<div class="eyebrow">LISTEN & PRACTICE</div><h1>英語のリズムを、耳から。</h1><div class="tabs">${['自由練習','問題'].map(m=>`<button class="${listeningMode===m?'active':''}" onclick="listeningMode='${m}';render()">${m}モード</button>`).join('')}</div><div class="player"><div class="eyebrow">${l.genre} · B2–C1</div><h2>${l.title}</h2><button class="play" aria-label="${playing?'停止':'音声を再生'}" onclick="toggleAudio()">${playing?'Ⅱ':'▶'}</button><p>${playing?'再生中':'聴いて、声に出してみましょう'}</p><label>再生速度 <select id="rate" aria-label="再生速度"><option value="0.8">0.8倍</option><option selected value="1">1.0倍</option><option value="1.2">1.2倍</option></select></label></div>${listeningMode==='問題'?`<section class="section"><h2>“${esc(words[l.word].en)}” の意味は？</h2><div class="choices section">${[words[l.word].ja,'一時的な','曖昧な'].map((a,i)=>`<button class="choice" onclick="toast('${i===0?'正解です！':'もう一度、聴いてみましょう'}')">${esc(a)}</button>`).join('')}</div></section>`:''}<details class="transcript"><summary>英文を確認する</summary>${l.text.map(p=>`<p>${esc(p)}</p>`).join('')}</details><div class="section"><button class="textbtn" onclick="go('articles')">ほかの教材を選ぶ →</button></div>`}
function stopAudio(){if('speechSynthesis'in window)window.speechSynthesis.cancel();playing=false}function toggleAudio(){if(playing){stopAudio();render();return}if(!('speechSynthesis'in window)){toast('このブラウザは音声読み上げに対応していません');return}const rate=Number(document.getElementById('rate').value),u=new SpeechSynthesisUtterance(lessons[selectedArticle].text.join(' '));u.lang='en-US';u.rate=rate;u.onend=()=>{playing=false;if(view==='listen')render()};u.onerror=()=>{playing=false;if(view==='listen')render();toast('音声を再生できませんでした')};playing=true;window.speechSynthesis.speak(u);render();document.getElementById('rate').value=String(rate)}
function addWord(){const en=prompt('保存したい英単語・表現を入力してください');if(!en?.trim())return;const ja=prompt('日本語の意味を入力してください');if(!ja?.trim())return;words.push({en:en.trim(),ja:ja.trim(),def:'',example:'',status:'学習中'});wordFilter='すべて';render();toast('保存しました')}
function manualTime(){const minutes=prompt('追加する学習時間（分）');if(minutes===null)return;const n=Number(minutes);if(!Number.isInteger(n)||n<=0||n>1440){toast('1〜1440分で入力してください');return}manualMinutes+=n;render();toast(`${n}分の学習を記録しました`)}
function render(){document.getElementById('app').innerHTML=({home,vocab:vocabulary,word:wordDetail,quiz,articles,article,listen:listening,records}[view]||home)();document.getElementById('nav').innerHTML=nav.map(([v,label])=>`<button class="navbtn ${(view===v||(v==='vocab'&&['word','quiz'].includes(view))||(v==='articles'&&view==='article'))?'active':''}" onclick="go('${v}')" aria-label="${label}" ${view===v?'aria-current="page"':''}>${ico(v)}${label}</button>`).join('');document.title=`${nav.find(([v])=>v===view)?.[1]||'English Notes'} · English Notes`}
if(location.hash==='#records')view='records';
render();
