(function(root){
 'use strict';
 let manifest=null,index=[],units=[],loadError=null,generation=0,hydrationPending=true,hydrationAttempt=0,initialized=false,initializationError=null,initializationPromise=null,collocationItems=[],collocationError=null,collocationPromise=null,genreItems=[],listeningItems=[];
 const cache=new Map(),pending=new Map(),listeners=new Set(),wordCache=new Map();
 const visible=(record,now=Date.now())=>Boolean(record.publishedAt&&Number.isFinite(Date.parse(record.publishedAt))&&Date.parse(record.publishedAt)<=now);
 async function digest(text){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('');}
 const adapter={async read(path){const result=await fetch(path,{cache:'no-cache'});if(!result.ok)throw Error('教材を取得できませんでした');return result.text();}};
 async function read(ref){if(!ref||!/^materials\/(articles|vocabulary|article-vocabulary|search|collocations|listening)\/[a-z0-9-]+\.json$/.test(ref.path))throw Error('Invalid material reference');if(cache.has(ref.path))return cache.get(ref.path);if(pending.has(ref.path))return pending.get(ref.path);const request=(async()=>{const text=await adapter.read(ref.path);if(await digest(text)!==ref.sha256)throw Error('教材の検証に失敗しました');const result=JSON.parse(text);if(ref.id&&result.id!==ref.id||ref.version&&result.version!==ref.version)throw Error('Material version mismatch');cache.set(ref.path,result);return result;})();pending.set(ref.path,request);try{return await request;}finally{pending.delete(ref.path);}}
 function notify(){for(const listener of listeners)listener();}
 function register(items){for(const item of items)wordCache.set(item.id,item);root.AppUI?.addCatalog(items);root.QuizUI?.registerItems(items);const catalog=root.AppUI?.syncCatalog?.();if(catalog)root.AppStorage?.setCatalog?.(catalog.items,catalog.legacyWords);}
 async function vocabulary(id){await api.ready;if(!initialized)throw initializationError||Error('教材を取得できませんでした');const article=index.find(a=>a.id===id&&visible(a));if(!article)throw Error('記事が見つかりません');const ref=manifest.articleVocabulary?.find(a=>a.id===id);if(!ref)throw Error('記事の語彙が見つかりません');const material=await read(ref);const items=material.items.map(v=>({...v,sourceKind:'article',articleId:id,materialVersion:article.version}));register(items);return items;}
 async function getWords(ids){await api.ready;if(!initialized)throw initializationError||Error('教材を取得できませんでした');const refs=[...new Set(ids.filter(id=>!wordCache.has(id)).map(id=>manifest.wordIndex?.[id]?.articleId).filter(Boolean))];await Promise.all(refs.map(vocabulary));const missing=ids.filter(id=>!wordCache.has(id));if(missing.length)throw Error('復習する語彙を取得できませんでした');return ids.map(id=>wordCache.get(id));}
 function loadCollocations(){const ref=manifest?.collocations;collocationPromise=(async()=>{try{if(!ref)return [];const material=await read(ref);if(!Array.isArray(material.items))throw Error('Invalid collocation material');collocationItems=material.items;collocationError=null;}catch(error){collocationItems=[];collocationError=error;console.error('コロケーションの読み込みに失敗しました',error);}repaint();return collocationItems;})();return collocationPromise;}
 function loadListening(){const ref=manifest?.listening;if(!ref)return Promise.resolve([]);return read(ref).then(material=>{listeningItems=Array.isArray(material.items)?material.items:[];repaint();return listeningItems;}).catch(error=>{listeningItems=[];console.error('リスニング教材の読み込みに失敗しました',error);return [];});}
 function repaint(){notify();if(typeof render==='function'&&!document.body.classList.contains('quiz-active'))render();}
 async function hydrate(){const token=generation,attempt=++hydrationAttempt,store=root.QuizUI?.getStore?.();hydrationPending=true;repaint();if(!store){hydrationPending=false;repaint();return;}try{await api.ready;if(!initialized){await initialize(true);if(!initialized)throw initializationError||Error('教材を取得できませんでした');}const resolvedIds=[...new Set([...(store.bookmarks||[]),...(store.logs||[]).map(e=>e.wordId)].filter(id=>manifest?.wordIndex?.[id]))];await getWords(resolvedIds);if(token!==generation||attempt!==hydrationAttempt)return;loadError=null;}catch(error){if(token===generation&&attempt===hydrationAttempt){loadError=error;console.error('保存した語彙の読み込みに失敗しました',error);}}finally{if(token===generation&&attempt===hydrationAttempt){hydrationPending=false;repaint();}}}

 const api={visible,articles:()=>index.filter(a=>visible(a)),listArticles:({category,level}={})=>index.filter(a=>visible(a)&&(!category||category==='すべて'||a.category===category)&&(!level||level==='すべて'||a.level===level)),units:()=>units.filter(a=>visible(a)),listening:()=>listeningItems,genres:()=>genreItems,sets:genreId=>units.filter(a=>visible(a)&&(!genreId||a.genre===genreId)).sort((a,b)=>a.setNumber-b.setNumber),collocations:()=>collocationItems,collocationError:()=>collocationError,async getCollocations(){await api.ready;return collocationPromise?collocationPromise:[];},items:()=>[...wordCache.values()],getArticleVocabulary:vocabulary,getWords,hydrateSaved:hydrate,error:()=>initializationError||loadError,hydrating:()=>hydrationPending,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn)},async getArticle(id){await api.ready;if(!initialized)throw initializationError||Error('教材を取得できませんでした');const ref=manifest.materials.find(a=>a.kind==='article'&&a.id===id&&visible(a));if(!ref)throw Error('記事が見つかりません');const [article]=await Promise.all([read(ref),vocabulary(id)]);return article;}};
 function initialize(retry=false){if(initializationPromise)return initializationPromise;if(retry)cache.clear();initializationPromise=(async()=>{try{const nextManifest=JSON.parse(await adapter.read('materials/manifest.json'));const metadata=await read(nextManifest.articleIndex);const search=nextManifest.articleSearch?await read(nextManifest.articleSearch):{articles:[]},genreMaterial=nextManifest.genres?await read(nextManifest.genres):{genres:[]};const nextUnits=await Promise.all(nextManifest.materials.filter(ref=>ref.kind==='vocabulary'&&visible(ref)).map(read));nextUnits.sort((a,b)=>a.level.localeCompare(b.level)||a.unitNumber-b.unitNumber);manifest=nextManifest;index=metadata.articles.map(a=>({...a,searchText:search.articles.find(x=>x.id===a.id)?.searchText||[a.title,a.summaryJa,a.category].join(" ")}));units=nextUnits;genreItems=genreMaterial.genres||[];const unit=units.find(x=>x.id===C1_UNIT_01.id);if(unit)Object.assign(C1_UNIT_01,unit);register(units.flatMap(x=>x.items));initialized=true;initializationError=null;loadError=null;loadCollocations();loadListening();repaint();return index;}catch(error){initialized=false;initializationError=error;loadError=error;index=[];units=[];hydrationPending=false;repaint();console.error('教材の読み込みに失敗しました',error);return [];}})();const request=initializationPromise;request.finally(()=>{if(initializationPromise===request)initializationPromise=null;});return request;}
 api.ready=initialize();

 root.MaterialCatalog=api;
 api.ready.then(()=>{if(initialized)hydrate();});
 root.AppStorage?.subscribe?.(event=>{if(event.reason==='user')generation++;if(['user','merge','import'].includes(event.reason))api.ready.then(hydrate);});
})(window);
