(function(){
 'use strict';
 const {QuizStore,QuizSession,chooseReview,chooseNextSet,scoreForMode,validateItem}=EnglishQuiz;
 const bank=[...C1_UNIT_01.items,...DEVELOPMENT_VOCABULARY.items].filter(validateItem);
 let sourceContext=null;
 let store=null,session=null,returnView='home',timer=null,overlay=null,error='',lastResult=null,focusBefore=null,toastTimer=null;
 try{store=new QuizStore(window.localStorage);}catch(e){error='回答履歴を読み込めません。ブラウザの保存設定を確認してください。';}
 const svg=(name)=>{const paths={close:'M6 6l12 12M18 6 6 18',more:'M5 12h.01M12 12h.01M19 12h.01',save:'M6 3h12v18l-6-4-6 4z',check:'m5 12 4 4L19 6',wrong:'M7 7l10 10M17 7 7 17',arrow:'m9 5 7 7-7 7'};return `<svg class="qs-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]}"/></svg>`;};
 const root=document.createElement('div');root.id='quiz-session';root.className='qs-root';root.hidden=true;document.body.append(root);
 const safe=s=>esc(s),modeName=m=>m==='en'?'英語 → 英語':'英語 → 日本語';
 function exampleHtml(item){const escaped=item.headword.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),pattern=new RegExp('\\b'+escaped+'(?:s|es|ed|ing)?\\b','gi');let result='',last=0;for(const match of item.example.matchAll(pattern)){result+=safe(item.example.slice(last,match.index))+'<strong>'+safe(match[0])+'</strong>';last=match.index+match[0].length;}return result+safe(item.example.slice(last));}
 const saved=id=>window.AppUI?AppUI.isSaved(id):!!store?.bookmarks.includes(id);
 const clearAuto=()=>{clearTimeout(timer);timer=null;};
 function notify(message){root.querySelector('.qs-toast')?.remove();const el=document.createElement('div');el.className='qs-toast';el.setAttribute('role','status');el.textContent=message;root.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),2000);}
 function activate(){focusBefore=document.activeElement;returnView=view;stopAudio();document.body.classList.add('quiz-active');root.hidden=false;}
 function launch(items,context=null){clearAuto();overlay=null;error='';lastResult=null;sourceContext=context;session=new QuizSession(items,store.settings.mode,store);draw();root.querySelector('.qs-close')?.focus({preventScroll:true});}
 function start(i){if(!store){activate();drawUnavailable();return;}activate();const linked=Number.isInteger(i)?bank.find(x=>x.headword.toLowerCase()===words[i]?.en.toLowerCase()):null;
   if(Number.isInteger(i)&&!linked){leave(returnView);toast('この表現の4択を準備してから練習できます');return;}
   const items=linked?[linked]:(window.AppUI?AppUI.reviewItems().slice(0,10):[]);if(!items.length){session=null;drawComplete();return;}launch(items);
 }
 function advanced(){startUnit();}
 function startUnit(){if(!store)return;if(root.hidden)activate();if(window.AppUI&&!AppUI.unitStarted()){leave();return;}launch(C1_UNIT_01.items,{kind:'unit',unitId:C1_UNIT_01.id});}
 function startWord(id){const item=bank.find(x=>x.id===id);if(!store||!item)return;if(root.hidden)activate();launch([item]);}
 function drawUnavailable(){root.innerHTML=`<div class="qs-frame qs-complete"><h1>履歴を保存できません</h1><p class="qs-status" role="alert">${safe(error)}</p><button class="qs-secondary" onclick="QuizUI.leave()">元の画面へ</button></div>`;}
 function drawComplete(){root.innerHTML=`<div class="qs-frame qs-complete"><h1>今日の復習は完了</h1><button class="qs-next" onclick="QuizUI.startUnit()">C1①から10問</button><button class="qs-plain" onclick="QuizUI.leave()">元の画面へ</button></div>`;}
 function draw(animateWrong=false){if(!session)return;if(session.state==='result'){drawResult();return;}const item=session.item,q=item.questions[session.mode],answer=session.answers[session.answers.length-1],answered=session.state!=='question',wrong=session.state==='wrong';
 root.innerHTML=`<div class="qs-frame ${wrong?'has-sheet':''}"><div class="qs-toolbar"><button class="qs-circle qs-close" aria-label="セッションを中断" onclick="QuizUI.interrupt()">${svg('close')}</button><div class="qs-progress" role="progressbar" aria-label="回答の進捗" aria-valuemin="0" aria-valuemax="${session.items.length}" aria-valuenow="${session.answers.length}"><i style="width:${session.answers.length/session.items.length*100}%"></i></div><button class="qs-circle" aria-label="セッション設定" onclick="QuizUI.menu()">${svg('more')}</button></div><div class="qs-content"><section class="qs-card" aria-label="問題"><div class="qs-count">${session.index+1} / ${session.items.length}</div><h1 class="qs-target">${safe(item.headword)}</h1>${session.mode==='en'?`<p class="qs-example">${safe(item.example)}</p>`:''}<button class="qs-circle qs-save ${saved(item.id)?'saved':''}" onclick="QuizUI.bookmark('${item.id}')" aria-label="${saved(item.id)?'保存を解除':'表現を保存'}" aria-pressed="${saved(item.id)}">${svg('save')}</button></section><div class="qs-answerarea"><div class="qs-skiprow">${answered?`<div class="qs-feedback ${wrong?'wrong':''}" role="status">${svg(wrong?'wrong':'check')}${wrong?(answer.skipped?'スキップしました':'正解を確認しよう'):'正解！'}</div>`:''}<button class="qs-circle qs-skip" aria-label="この問題をスキップ" onclick="QuizUI.skip()" ${answered?'disabled':''}>SKIP</button></div><div class="qs-options">${q.choices.map((choice,i)=>{const correct=answered&&i===q.answerIndex,incorrect=answered&&!answer.correct&&i===answer.selectedIndex;return `<button class="qs-option ${correct?'correct':''} ${incorrect?'wrong':''} ${incorrect&&animateWrong?'qs-wrong-enter':''}" onclick="QuizUI.answer(${i})" ${answered?'disabled':''}><span class="qs-number">${i+1}</span><span class="qs-answertext">${safe(choice)}</span>${correct?svg('check'):incorrect?svg('wrong'):''}</button>`;}).join('')}</div>${session.state==='correct'&&!store.settings.autoAdvance?'<button class="qs-next" onclick="QuizUI.next()">次へ</button>':''}${error?`<p class="qs-status" role="alert">${safe(error)}</p>`:''}</div></div>${wrong?`<section class="qs-sheet" aria-label="意味と解説"><h2>${safe(item.meaning)}</h2><p>${exampleHtml(item)}</p><p class="qs-definition"><span class="qs-definition-label">定義</span>${safe(item.definition)}</p><button class="qs-next" onclick="QuizUI.next()">次へ</button></section>`:''}</div>`;
 if(overlay)drawOverlay();
 }
 function submit(index,isSkip=false){if(!session||overlay)return;let event;try{event=isSkip?session.skip():session.answer(index);}catch(e){error='回答を保存できませんでした。空き容量や保存設定を確認して、もう一度回答してください。';draw();return;}if(!event)return;error='';if(typeof navigator.vibrate==='function')navigator.vibrate(event.correct?18:[22,35,22]);draw(!event.correct&&!event.skipped);if(event.correct&&store.settings.autoAdvance)scheduleAuto();}
 function scheduleAuto(){clearAuto();if(session?.state==='correct'&&store.settings.autoAdvance&&!overlay)timer=setTimeout(next,700);}
 function next(){if(!session||overlay||!['correct','wrong'].includes(session.state))return;clearAuto();session.next();draw();}
 function drawResult(){lastResult=session.result();if(sourceContext?.kind==='unit'&&window.AppUI)error=AppUI.unitCompleted(session)?'':'ユニットの成績を保存できませんでした。';const r=lastResult,totalScore=scoreForMode(store.logs,r.mode),seconds=Math.round(r.durationMs/1000),duration=`${Math.floor(seconds/60)}分${String(seconds%60).padStart(2,'0')}秒`;
 root.innerHTML=`<div class="qs-frame qs-result"><div class="qs-toolbar"><button class="qs-circle" aria-label="元の画面へ戻る" onclick="QuizUI.leave()">${svg('close')}</button></div><div class="qs-score"><div class="qs-resultlabel">おつかれさまでした</div><strong>${r.correct} <span>/ ${r.total}</span></strong><p>所要時間 ${duration} · ${modeName(r.mode)}</p><p class="qs-modegrade">このモードの累計 ${totalScore.correct} / ${totalScore.answered}問正解</p></div><section><h2>もう一度見返したい言葉</h2>${r.wrongItems.length?`<div class="qs-wronglist">${r.wrongItems.map(item=>`<button class="qs-wrongrow ${saved(item.id)?'saved':''}" onclick="QuizUI.bookmark('${item.id}')" aria-pressed="${saved(item.id)}" aria-label="${safe(item.headword)} ${saved(item.id)?'保存を解除':'保存する'}"><span><strong>${safe(item.headword)}</strong><small>${safe(item.meaning)}</small></span>${svg('save')}</button>`).join('')}</div>`:'<p class="qs-empty">すべて正解。よくできました！</p>'}</section>${error?`<p class="qs-status" role="alert">${safe(error)}</p><button class="qs-secondary" onclick="QuizUI.saveResult()">履歴の保存を再試行</button>`:''}<div class="qs-resultactions"><button class="qs-next" onclick="QuizUI.retry()" ${r.wrongItems.length?'':'disabled'}>間違えた語だけもう一度</button>${sourceContext?.kind==='unit'?'':'<button class="qs-secondary" onclick="QuizUI.nextSet()">次の10問</button>'}<button class="qs-plain" onclick="QuizUI.home()">ホームへ</button></div></div>`;
 }
 function bookmark(id){try{if(window.AppUI)AppUI.toggleBookmark(id);else store.toggleBookmark(id);if(session?.state==='result')drawResult();else draw();notify(saved(id)?'保存しました':'保存を解除しました');}catch(e){notify('保存できませんでした。もう一度お試しください');}}
 function openOverlay(type){clearAuto();overlay=type;drawOverlay();}
 function drawOverlay(){root.querySelector('.qs-overlay')?.remove();const el=document.createElement('div');el.className='qs-overlay';el.innerHTML=overlay==='menu'?`<div class="qs-dialog qs-menu" role="dialog" aria-modal="true" aria-label="セッション設定"><button class="qs-menubutton" onclick="QuizUI.switchMode()">出題モード切替<span>${modeName(store.settings.mode)}</span></button><button class="qs-menubutton" onclick="QuizUI.toggleAuto()">自動送りON/OFF<span>${store.settings.autoAdvance?'ON':'OFF'}</span></button><button class="qs-menubutton" onclick="QuizUI.interrupt()">中断<span>×</span></button></div>`:`<div class="qs-dialog" role="dialog" aria-modal="true" aria-labelledby="qs-interrupt-title"><h2 id="qs-interrupt-title">中断しますか</h2><p>回答した${session?.answers.length||0}問の結果は保存済みです。</p><button class="qs-next" onclick="QuizUI.leave()">中断して戻る</button><button class="qs-secondary" onclick="QuizUI.closeOverlay()">続ける</button></div>`;el.addEventListener('click',e=>{if(e.target===el)closeOverlay()});root.append(el);el.querySelector('button')?.focus();}
 function closeOverlay(){overlay=null;root.querySelector('.qs-overlay')?.remove();scheduleAuto();}
 function settings(patch){try{store.setSettings(patch);}catch(e){notify('設定を保存できませんでした');return false;}return true;}
 function switchMode(){if(settings({mode:store.settings.mode==='ja'?'en':'ja'})){drawOverlay();notify('次のセットから '+modeName(store.settings.mode));}}
 function toggleAuto(){if(settings({autoAdvance:!store.settings.autoAdvance})){draw();if(overlay)drawOverlay();}}
 function interrupt(){if(!session||session.state==='result'){leave();return;}openOverlay('interrupt');}
 function leave(destination=returnView){clearAuto();overlay=null;session=null;root.hidden=true;root.innerHTML='';document.body.classList.remove('quiz-active');go(destination);focusBefore?.focus?.({preventScroll:true});}
 function retry(){if(!lastResult?.wrongItems.length)return;const retryItems=[...lastResult.wrongItems];launch(retryItems);}
 function nextSet(){const previous=new Set(session.items.map(x=>x.id)),items=(window.AppUI?AppUI.reviewItems():[]).filter(x=>!previous.has(x.id)).slice(0,10);if(items.length)launch(items);else{session=null;drawComplete();}}
 startReview=start;
 window.QuizUI={answer:i=>submit(i),skip:()=>submit(null,true),next,bookmark,saveResult:drawResult,menu:()=>openOverlay('menu'),interrupt,closeOverlay,switchMode,toggleAuto,retry,nextSet,advanced,startUnit,startWord,getStore:()=>store,leave:()=>leave(),home:()=>leave('home')};
 document.addEventListener('keydown',e=>{if(root.hidden)return;if(overlay){if(e.key==='Escape'){e.preventDefault();closeOverlay();return;}if(e.key==='Tab'){const buttons=[...root.querySelectorAll('.qs-overlay button')],first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return;}if(e.key==='Escape'){e.preventDefault();interrupt();return;}if(e.repeat)return;if(session?.state==='question'&&/^[1-4]$/.test(e.key)){e.preventDefault();submit(Number(e.key)-1);}else if(session&&['correct','wrong'].includes(session.state)&&['Enter',' '].includes(e.key)){e.preventDefault();next();}},true);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)clearAuto();else scheduleAuto();});
 render();
})();
