(function(){
 'use strict';
 const quizStore=QuizUI.getStore();
 let appState=null;
 try{appState=new LearningState.AppState(localStorage,C1_UNIT_01,DEVELOPMENT_VOCABULARY.items);}catch(e){toast('保存情報を読み込めませんでした');}
 const allItems=[...C1_UNIT_01.items,...DEVELOPMENT_VOCABULARY.items];
 const personIcon='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></svg>';
 const arrow=()=>'<span class="action-chevron" aria-hidden="true">›</span>';
 let vocabularyTab='saved',vocabularyLevel='C1',savedFilter='すべて',detailItem=null;
 nav.splice(0,nav.length,['home','ホーム'],['vocab','単語'],['articles','記事'],['listen','リスニング'],['records','記録']);
 if(appState){for(const index of appState.articleSaves)if(words[index])words[index].bookmarked=true;for(const word of appState.customWords)if(!words.some(x=>x.en===word.en&&x.ja===word.ja))words.push({...word});}
 function savedWords(){return appState?appState.savedVocabulary(quizStore?.bookmarks||[],words):[];}
 function savedIds(){return savedWords().filter(x=>x.id).map(x=>x.id);}
 function status(item){return appState&&quizStore?appState.wordStatus(item.id,quizStore.logs,quizStore.settings.mode):'未学習';}
 const statusClass=value=>({'未学習':'new','復習予定':'review','学習中':'learning','定着':'retained'}[value]);
 vocabulary=function(){const entries=savedWords(),states=['すべて','未学習','復習予定','学習中','定着'];
  const tabs=`<div class="vocabulary-tabs" role="tablist" aria-label="単語教材">${[['saved','保存した語'],['units','上級語彙集']].map(([key,label])=>`<button role="tab" aria-selected="${vocabularyTab===key}" onclick="AppUI.vocabularyTab('${key}')">${label}</button>`).join('')}</div>`;
  let content;
  if(vocabularyTab==='saved'){const filtered=entries.filter(item=>savedFilter==='すべて'||status(item)===savedFilter);content=`<div class="saved-filters" aria-label="保存した語の状態">${states.map(label=>`<button aria-pressed="${savedFilter===label}" onclick="AppUI.filterWords('${label}')">${label} <span>${entries.filter(item=>label==='すべて'||status(item)===label).length}</span></button>`).join('')}</div><div class="vocabulary-group">${filtered.map(item=>{const state=status(item),index=entries.indexOf(item);return `<button class="vocabulary-row" onclick="AppUI.savedDetail(${index})"><span class="vocabulary-label"><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span><span class="word-state word-state-${statusClass(state)}">${state}</span>${arrow()}</button>`;}).join('')||`<p class="vocabulary-empty">${entries.length?'この状態の語はありません':'保存した語はありません'}</p>`}</div>${reviewItems().length?`<div class="vocabulary-actions"><button class="primary full" onclick="startReview()">復習をはじめる ${arrow()}</button></div>`:''}`;
  }else{const best=appState&&quizStore?appState.best(quizStore.settings.mode):null;content=`<div class="level-switch" role="tablist" aria-label="語彙レベル">${['C1','C2'].map(level=>`<button role="tab" aria-selected="${vocabularyLevel===level}" onclick="AppUI.vocabularyLevel('${level}')">${level}</button>`).join('')}</div>${vocabularyLevel==='C1'?`<div class="vocabulary-group"><button class="vocabulary-row unit-row" ${quizStore&&appState?'onclick="QuizUI.startUnit()"':'disabled'}><span class="unit-number">①</span><span class="vocabulary-label"><strong>C1①</strong><small>${best===10?'クリア':best===null?'未着手':'学習中'}</small></span><span class="unit-score">${best??0} / 10</span>${arrow()}</button></div>`:'<p class="vocabulary-empty">教材はありません</p>'}<button class="textbtn vocabulary-credit" onclick="AppUI.showCredits()">教材の出典 ${arrow()}</button>`;}
  return `<div class="sectionhead"><h1>単語・表現</h1>${vocabularyTab==='saved'?'<button class="textbtn" onclick="addWord()">＋ 追加</button>':''}</div>${tabs}${content}`;
 };
 wordDetail=function(){const item=detailItem||savedWords().find(x=>x.headword.toLowerCase()===words[selectedWord]?.en.toLowerCase());if(!item)return '<button class="textbtn" onclick="go(\'vocab\')">単語・表現へ ›</button>';const state=status(item);return `<button class="back" onclick="go('vocab')">単語・表現へ ${arrow()}</button><span class="word-state word-state-${statusClass(state)}">${state}</span><div class="flash"><strong>${esc(item.headword)}</strong><p>${esc(item.meaning)}</p></div><div class="wordmeaning"><h3>${esc(item.definition||'')}</h3><p>${esc(item.example||'')}</p></div>${item.id?`<button class="primary full" onclick="QuizUI.startWord('${item.id}')">この表現を練習する ${arrow()}</button>`:''}`;};
 function reviewItems(){return appState&&quizStore?appState.reviewCandidates(quizStore.logs,savedIds(),quizStore.settings.mode).filter(EnglishQuiz.validateItem):[];}
 home=function(){
  const count=reviewItems().length,date=new Date(),dateText=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'long'}).format(date),hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'numeric',hourCycle:'h23'}).format(date)),greeting=hour<11?'おはようございます':hour<18?'こんにちは':'こんばんは';
  const best=quizStore&&appState?appState.best(quizStore.settings.mode):null,last=appState?.lastUnit,modeText=quizStore?.settings.mode==='en'?'英語 → 英語':'英語 → 日本語';
  const articles=lessons.map((lesson,index)=>({lesson,index})).filter(({lesson})=>lesson.status==='checked'&&lesson.publishedAt&&Number.isFinite(Date.parse(lesson.publishedAt))&&Date.parse(lesson.publishedAt)<=Date.now()).sort((a,b)=>Date.parse(b.lesson.publishedAt)-Date.parse(a.lesson.publishedAt)).slice(0,3);
  return `<div class="home-greeting"><small>${esc(dateText)} · ${greeting}</small><h1>今日の学習</h1></div><section class="home-review" aria-labelledby="home-review-title"><div class="home-review-label" id="home-review-title">今日の復習</div>${count?`<div class="home-review-count"><strong>${count}</strong><span>語</span></div><p class="home-review-caption">${modeText}で、覚えた言葉を思い出しましょう。</p>`:'<div class="home-review-complete"><span aria-hidden="true">✓</span><h2>今日の復習は完了</h2></div>'}${quizStore&&appState?`<button class="home-primary" onclick="${count?'startReview()':'QuizUI.startUnit()'}">${count?'復習をはじめる':'C1①から10問'} ${arrow()}</button>`:''}</section>${last&&last.unitId===C1_UNIT_01.id?`<section class="home-section"><div class="home-section-head"><h2>続きから</h2></div><button class="home-resume-row" onclick="QuizUI.startUnit()"><span><strong>C1①${best===null?'':' · ベスト '+best+'/10'}</strong><small>${modeText} · ${best===10?'クリア':best===null?'未完了':'もう一度挑戦する'}</small></span>${arrow()}</button></section>`:''}${articles.length?`<section class="home-section"><div class="home-section-head"><h2>新着記事</h2></div>${articles.map(({lesson,index})=>{const minutes=lesson.readingMinutes||Math.max(1,Math.ceil(lesson.text.join(' ').split(/\s+/).length/200));return `<button class="home-article-row" onclick="lessonOpen(${index})"><label>${esc(lesson.genre)}</label><h3>${esc(lesson.title)}</h3><small>約${minutes}分</small></button>`;}).join('')}</section>`:''}<section class="home-section"><div class="home-section-head"><h2>表現ノート</h2></div><button class="home-note-row" onclick="AppUI.showSaved()"><span><strong>保存した語 ${savedWords().length}件</strong><small>一覧を見る</small></span>${arrow()}</button></section>`;
 };
 const account=document.createElement('dialog');account.id='app-settings';document.body.append(account);
 function openSettings(){if(!quizStore||!appState){toast('保存設定を確認してください');return;}const goals=appState.goals;account.innerHTML=`<form class="settings-sheet"><div class="settings-header"><h2>設定</h2><button type="button" aria-label="設定を閉じる" onclick="AppUI.closeSettings()">×</button></div><div class="settings-fields"><label>日目標（分）<input name="daily" type="number" min="1" max="1440" step="1" value="${goals.daily??''}" placeholder="設定しない"></label><label>週目標（分）<input name="weekly" type="number" min="1" max="10080" step="1" value="${goals.weekly??''}" placeholder="設定しない"></label><label>出題モード<select name="mode"><option value="ja" ${quizStore.settings.mode==='ja'?'selected':''}>英語 → 日本語</option><option value="en" ${quizStore.settings.mode==='en'?'selected':''}>英語 → 英語</option></select></label><label><input name="auto" type="checkbox" ${quizStore.settings.autoAdvance?'checked':''}>正解したら自動で次へ</label></div><div class="settings-actions"><button type="button" onclick="AppUI.closeSettings()">閉じる</button><button type="submit">保存する</button></div><button class="textbtn" type="button" onclick="AppUI.openCredits()">教材の出典</button></form>`;
  account.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,goal=name=>form.elements[name].value.trim()===''?null:Number(form.elements[name].value);try{appState.savePreferences(quizStore,{daily:goal('daily'),weekly:goal('weekly')},{mode:form.elements.mode.value,autoAdvance:form.elements.auto.checked},EnglishQuiz.KEYS.settings);account.close();render();toast('設定を保存しました');}catch(error){toast('設定を保存できませんでした');}});account.showModal();
 }
 account.addEventListener('click',e=>{if(e.target===account){const box=account.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)account.close();}});
 function openNotes(){const entries=savedWords();account.innerHTML=`<div class="settings-sheet"><div class="settings-header"><h2>表現ノート</h2><button aria-label="表現ノートを閉じる" onclick="AppUI.closeSettings()">×</button></div>${entries.length?entries.map(item=>item.id?`<button class="home-resume-row" onclick="AppUI.openSaved('${item.id}')"><span><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span>${arrow()}</button>`:`<div class="home-resume-row"><span><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span></div>`).join(''):'<p class="muted">保存した語はありません</p>'}</div>`;account.showModal();}
 function openCredits(){account.innerHTML=`<div class="settings-sheet"><div class="settings-header"><h2>教材の出典</h2><button aria-label="出典を閉じる" onclick="AppUI.closeSettings()">×</button></div><h3>Octanove Vocabulary Profile C1/C2 v1.0</h3><p>Octanove Labs</p><p><a href="https://github.com/openlanguageprofiles/olp-en-cefrj" target="_blank" rel="noopener noreferrer">語彙リスト・利用条件</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a></p><p>CEFR-J／Octanove Vocabulary Profileのレベル付けに基づく目安</p><p>語を抽出し独自の順序で構成。意味・定義・例文・選択肢・解説は本アプリ向けに作成しています。C1①の教材データはCC BY-SA 4.0で提供します。</p></div>`;}
 const originalSave=saveArticleWord;
 saveArticleWord=function(){try{if(!appState)throw Error('storage');const index=lessons[selectedArticle].word,item=allItems.find(x=>x.headword.toLowerCase()===words[index].en.toLowerCase());appState.setSavedState(quizStore,item?[...quizStore.bookmarks,item.id]:quizStore.bookmarks,[...appState.articleSaves,index],EnglishQuiz.KEYS.bookmarks);originalSave();}catch(e){toast('保存できませんでした');}};
 const originalAdd=addWord;
 addWord=function(){if(!appState){toast('保存できませんでした');return;}const count=words.length;originalAdd();if(words.length>count&&appState){try{appState.addCustomWord(words[words.length-1]);render();}catch(e){words.splice(count);render();toast('保存できませんでした');}}};
 const originalRender=render;
 render=function(){originalRender();document.body.dataset.view=view;
  const active=view==='word'||view==='quiz'?'vocab':view==='article'?'articles':view;
  const links=nav.map(([page,label])=>`<button class="navbtn ${active===page?'active':''}" onclick="go('${page}')" ${active===page?'aria-current="page"':''}>${ico(page)}<span>${label}</span></button>`).join('');
  document.getElementById('nav').innerHTML=links;document.querySelector('.side-links').innerHTML=links;
  document.querySelectorAll('#app .meta,#app .eyebrow').forEach(el=>{el.textContent=el.textContent.replace(/\s*·\s*B2[–〜~-]C1/g,'');});
  document.querySelectorAll('#app button').forEach(button=>{const walker=document.createTreeWalker(button,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))node.textContent=node.textContent.replace(/→(?=\s*$)|←/g,'›');});
 };
 document.querySelector('header').className='app-header';document.querySelector('header').innerHTML=`<div class="brand">English Notes</div><button class="account-button" aria-label="アカウント設定" onclick="AppUI.openSettings()">${personIcon}</button>`;
 const side=document.createElement('aside');side.className='side-nav';side.innerHTML=`<div class="side-brand">English Notes</div><nav class="side-links" aria-label="メインメニュー"></nav><button class="side-account" onclick="AppUI.openSettings()">${personIcon}<span>アカウント</span></button>`;document.body.prepend(side);
 window.AppUI={vocabularyTab:tab=>{vocabularyTab=tab;render();},vocabularyLevel:level=>{vocabularyLevel=level;render();},filterWords:filter=>{savedFilter=filter;render();},savedDetail:index=>{detailItem=savedWords()[index];go('word');},showSaved:()=>{vocabularyTab='saved';savedFilter='すべて';go('vocab');},showCredits:()=>{openCredits();account.showModal();},reviewItems,openSettings,openCredits,closeSettings:()=>account.close(),openNotes,openSaved:id=>{account.close();detailItem=savedWords().find(x=>x.id===id);if(detailItem)go('word');},unitStarted:()=>{try{appState.startUnit(quizStore.settings.mode);return true;}catch(e){toast('学習履歴を保存できませんでした');return false;}},isSaved:id=>savedIds().includes(id),toggleBookmark:id=>{const removing=savedIds().includes(id),item=allItems.find(x=>x.id===id),indexes=words.map((w,i)=>({w,i})).filter(({w})=>item&&w.en.toLowerCase()===item.headword.toLowerCase()).map(({i})=>i);appState.setSavedState(quizStore,removing?quizStore.bookmarks.filter(x=>x!==id):[...quizStore.bookmarks,id],removing?appState.articleSaves.filter(i=>!indexes.includes(i)):appState.articleSaves,EnglishQuiz.KEYS.bookmarks,removing&&item?[...appState.unsavedCustomWords,item.headword.trim().toLowerCase()]:appState.unsavedCustomWords);if(removing)for(const i of indexes)words[i].bookmarked=false;},unitCompleted:session=>{try{appState.completeUnit(session);return true;}catch(e){return false;}}};
 const theme=document.querySelector('meta[name="theme-color"]');if(theme)theme.content=getComputedStyle(document.documentElement).getPropertyValue('--color-bg').trim();
 render();
})();
