(function(){
 'use strict';
 const READ_KEY='english-notes.article.read.v1',DRAFT_KEY='english-notes.article.opinion.v1',ANSWER_KEY='english-notes.article.answers.v1';
 const state={category:'すべて',selected:null,orders:new Map(),answers:new Map(),selection:null,activeWord:null,level:'すべて',loaded:null,loading:false,loadError:false,epoch:0,translations:new Set(),allTranslations:false};
 function saveAnswer(a,q,choiceId){const events=readStore(ANSWER_KEY),eventId=crypto.randomUUID();events[eventId]={eventId,questionId:q.id,articleId:a.id,wordId:null,materialVersion:a.version,selectedChoiceId:choiceId,correctChoiceId:q.correctChoiceId,correct:choiceId===q.correctChoiceId,skipped:false,answeredAt:new Date().toISOString(),kind:'comprehension',mode:'en',sessionId:state.readSession};return writeStore(ANSWER_KEY,events)}
 const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeUrl=value=>{try{const u=new URL(value,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
 const storage=window.AppStorage||localStorage;
 const readStore=key=>{try{const val=JSON.parse(storage.getItem(key)||'{}');return val&&typeof val==='object'&&!Array.isArray(val)?val:{}}catch{return {}}};
 function writeStore(key,value){try{storage.setItem(key,JSON.stringify(value));return true}catch{toast('保存できませんでした');return false}}
 const catalogue=()=>window.MaterialCatalog?.articles?.()||[];
 const current=()=>state.loaded?.id===state.selected?state.loaded:catalogue().find(a=>a.id===state.selected&&a.paragraphs)||null;
 const read=a=>Boolean(readStore(READ_KEY)[a.id]?.completedAt);
 const saved=w=>Boolean(window.AppUI?.isSaved?.(w.id));
 function published(value){const d=new Date(value);return Number.isFinite(d.getTime())?'元記事 '+new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric'}).format(d):''}
 function meta(a){return `<div class="a5-meta"><span class="a7-level">${e(a.level)}</span><span>${e(a.category)}</span><span>約${e(a.readingMinutes)}分</span><span>${e(published(a.sourcePublishedAt||a.sources?.[0]?.publishedAt))}</span></div>`}
 function photo(a,withCredit=false){const p=a.photo;if(!p?.assetPath)return '<div class="a5-photo-fallback" aria-hidden="true">'+ico('articles')+'</div>';const url=safeUrl(p.pageUrl);return `<figure class="a5-photo"><img src="${e(p.assetPath)}" alt="${e(p.alt)}" loading="lazy">${withCredit?`<figcaption>${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(p.credit)}</a>`:e(p.credit)}</figcaption>`:''}</figure>`}
 function status(a){return read(a)?'<span class="a5-read-status"><span aria-hidden="true">✓</span>読了</span>':''}
 function open(id){if(!catalogue().some(a=>a.id===id)){toast('記事を読み込めませんでした');return}const epoch=++state.epoch;state.selected=id;state.loaded=null;state.loading=true;state.loadError=false;state.readSession=crypto.randomUUID();state.activeWord=null;state.selection=null;state.orders.clear();state.answers.clear();state.translations.clear();state.allTranslations=false;
  if(!window.MaterialCatalog?.getArticle){state.loaded=catalogue().find(a=>a.id===id);state.loading=false;go('article');return}
  go('article');Promise.resolve(window.MaterialCatalog.getArticle(id)).then(a=>{if(epoch!==state.epoch)return;state.loaded=a;state.loading=false;if(view==='article')render()}).catch(()=>{if(epoch!==state.epoch)return;state.loading=false;state.loadError=true;if(view==='article')render()});
 }
 const Browse=window.ArticleBrowse;
 const browseFilters=Browse.route(location.href);let searchOpen=Boolean(browseFilters.q),searchTimer=null,queryDraft=browseFilters.q,composing=false;
 function list(){return Browse.render(catalogue(),browseFilters,{isRead:read,searchOpen});}
 function updateBrowse(filters,focusSearch=false){const previousInput=document.querySelector?.('[data-ab-search]'),keepFocus=focusSearch&&document.activeElement===previousInput,start=previousInput?.selectionStart,end=previousInput?.selectionEnd;clearTimeout(searchTimer);Object.assign(browseFilters,{category:'',level:'',q:'',list:false},filters);queryDraft=browseFilters.q;window.history?.pushState({articleBrowse:true},'',Browse.url(location.href,browseFilters));if(view!=='articles')go('articles');else rerender();if(keepFocus){const input=document.querySelector('[data-ab-search]');input?.focus();if(start!==null&&start!==undefined)input?.setSelectionRange?.(start,end);}}
 window.addEventListener?.('popstate',event=>{clearTimeout(searchTimer);Object.assign(browseFilters,Browse.route(location.href));queryDraft=browseFilters.q;composing=false;searchOpen=Boolean(browseFilters.q);if(view==='articles'||event.state?.articleBrowse||browseFilters.category||browseFilters.level||browseFilters.q||browseFilters.list)go('articles');});

 function sources(a){const first=a.sources[0],month=String(first.publishedAt||'').slice(0,7).replace(/^(\d{4})-(\d{2})$/,'$1年$2月');return `<section class="a5-source"><div class="a5-source-summary"><p>出典：${e(first.publisher)}（${e(month)}） · ${e(a.editorialNotice)}</p><button class="a5-secondary" data-a5-source-toggle aria-expanded="false" aria-controls="a5-source-details">詳細</button></div><div id="a5-source-details" hidden><ul>${(a.sources||[]).map(s=>`<li><a href="${e(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${e(s.title)}</a><p>${e(s.publisher)}${s.author?' · '+e(s.author):''}${s.authors?.length?' · '+e(s.authors.join(', ')):''} · ${e(s.dateKind==='inscription-year'?'登録年 '+s.publishedAt:s.publishedAt)}${s.dateNote?' · '+e(s.dateNote):''}<br>出典確認日 ${e(s.checkedAt)}</p></li>`).join('')}</ul></div></section>`}
 function bookmarkButton(w){const active=saved(w);return `<button class="a5-secondary a5-bookmark ${active?'saved':''}" data-a5-save="${e(w.id)}" aria-label="${e(w.headword)} ${active?'保存を解除':'保存する'}" aria-pressed="${active}"><svg viewBox="0 0 24 24" fill="${active?'currentColor':'none'}" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4z"/></svg></button>`}
 function evidence(q){return (q.evidence||[]).map(part=>{let text=e(part.text);for(const phrase of part.highlights)text=text.replace(e(phrase),`<strong>${e(phrase)}</strong>`);return `<blockquote><a class="a5-paragraph-label" href="#a5-${e(part.paragraphId)}">${e(part.paragraphId.toUpperCase())}</a> ${text}</blockquote>`}).join('')}
 function paragraphs(a){return (a.paragraphs||[]).map(p=>{const words=(a.vocabulary||[]).filter(w=>w.contextParagraphId===p.id);let parts=[{text:p.text}];for(const w of words){const form=w.surfaceForm||w.headword;if(!form)continue;const pattern=new RegExp('\\b'+form.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','ig');parts=parts.flatMap(part=>{if(part.word)return [part];const result=[];let start=0;for(const match of part.text.matchAll(pattern)){result.push({text:part.text.slice(start,match.index)},{text:match[0],word:w.id});start=match.index+match[0].length}result.push({text:part.text.slice(start)});return result})}return `<div class="a7-paragraph"><p id="a5-${e(p.id)}" data-a5-paragraph="${e(p.id)}">${parts.map(part=>part.word?`<button class="a5-keyword" data-a5-word="${e(part.word)}">${e(part.text)}</button>`:e(part.text)).join('')}</p><button class="a7-translation-button" data-a7-translation="${e(p.id)}" aria-expanded="${state.allTranslations||state.translations.has(p.id)}" aria-controls="a7-ja-${e(p.id)}">${state.allTranslations||state.translations.has(p.id)?'訳を閉じる':'訳を見る'}</button><p class="a7-translation" id="a7-ja-${e(p.id)}" ${state.allTranslations||state.translations.has(p.id)?'':'hidden'}>${e(p.translationJa)}</p></div>`}).join('')}
 function wordBlock(a){return `<section class="a5-section"><h2>この記事の単語・表現</h2><div class="a5-vocab">${(a.vocabulary||[]).map(w=>`<div class="a5-wordrow"><div><strong>${e(w.headword)}</strong><p>${e(w.meaning)}</p><p class="a5-example">${e(w.example)}</p></div>${bookmarkButton(w)}</div>`).join('')}</div>${a.vocabulary?.length?'<button class="a5-secondary a5-quiz-entry" data-a5-quiz>単語を確認する</button>':''}</section>`}
 function ordered(a,q){const key=a.id+':'+a.version+':'+q.id;if(!state.orders.has(key)){let options;if(window.EnglishQuiz?.shuffleChoices)options=window.EnglishQuiz.shuffleChoices(q);else{options=q.choices.map((text,i)=>({id:q.choiceIds[i],text}));for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}}state.orders.set(key,options)}return state.orders.get(key)}
 function questions(a){return `<section class="a5-section"><h2>内容を確認する</h2>${(a.comprehension||[]).map((q,n)=>{const key=a.id+':'+a.version+':'+q.id,chosen=state.answers.get(key),done=chosen!==undefined;return `<section class="a5-question"><h3>${n+1}. ${e(q.question)}</h3><div class="a5-options">${ordered(a,q).map((choice,i)=>`<button class="a5-secondary a5-option ${done?(choice.id===q.correctChoiceId?'correct':choice.id===chosen?'wrong':''):''}" data-a5-answer="${e(q.id)}" data-choice="${e(choice.id)}" ${done?'disabled':''}><small>${i+1}</small><span>${e(choice.text)}</span>${done&&choice.id===q.correctChoiceId?'<span aria-label="正解">✓</span>':done&&choice.id===chosen?'<span aria-label="誤答">×</span>':''}</button>`).join('')}</div>${done?`<div class="a5-evidence" role="status"><strong>${chosen===q.correctChoiceId?'正解です':'正解を確認しましょう'}</strong><p>${e(q.explanationJa)}</p>${evidence(q)}</div>`:''}</section>`}).join('')}</section>`}
 function detail(){const a=current();if(!a)return `<button class="back" data-a5-list>‹ 記事</button>${state.loading?'<p class="a5-empty" role="status">読み込んでいます</p>':state.loadError?'<p class="a5-empty" role="alert">記事を読み込めませんでした</p><button class="a5-secondary" data-a7-retry>再試行</button>':'<p class="a5-empty">記事を選択してください</p>'}`;const draft=readStore(DRAFT_KEY)[a.id]?.text||'';return `<button class="back" data-a5-list>‹ 記事</button>${photo(a,true)}<div class="a5-heading">${meta(a)}<h1>${e(a.title)}</h1><p class="a5-summary">${e(a.summaryJa)}</p></div>${sources(a)}${wordBlock(a)}<section class="a5-section"><div class="a7-body-heading"><h2>本文</h2><label class="a7-all-translations"><input type="checkbox" data-a7-all-translations ${state.allTranslations?'checked':''}>日本語訳をすべて表示</label></div><div id="a5-meaning" class="a5-meaning" hidden></div><div class="a5-body" id="a5-body" tabindex="0" aria-label="英文本文、文字を選択して表現を保存">${paragraphs(a)}</div><div class="a5-selection" id="a5-selection" hidden><span id="a5-selection-text"></span><button class="a5-secondary" data-a5-selection-save>選んだ表現を保存</button><button class="a5-close" data-a5-selection-close aria-label="選択を閉じる">×</button></div></section>${questions(a)}${a.opinion?`<section class="a5-section a5-opinion"><h2>自分の意見を書く（任意）</h2><label class="a5-opinion-label" for="a5-opinion">${e(a.opinion.prompt)}</label><textarea id="a5-opinion" data-a5-opinion placeholder="英語で自分の考えを書く">${e(draft)}</textarea><p class="a5-draft-status" id="a5-draft-status">${draft?'この端末に保存した下書き':''}</p></section>`:''}<button class="primary a5-mark-read" data-a5-read>${read(a)?'読了済み ✓':'読了にする'}</button>`}
 function rerender(){const scroll=window.scrollY;render();window.scrollTo(0,scroll)}
 function word(id){return current()?.vocabulary?.find(w=>w.id===id)}
 function saveWord(id){const w=word(id);if(!w)return;try{if(!window.AppUI?.saveMaterialWord)throw Error('save hook unavailable');const result=saved(w)?window.AppUI.toggleBookmark(w.id):window.AppUI.saveMaterialWord(w);if(result===false)throw Error('save rejected');document.querySelectorAll('[data-a5-save]').forEach(b=>{if(b.dataset.a5Save===id)b.outerHTML=bookmarkButton(w)});toast(saved(w)?'単語・表現に保存しました':'保存を解除しました')}catch{toast('保存できませんでした')}}
 function meaning(id){const w=word(id),box=document.getElementById('a5-meaning');if(!w||!box)return;box.innerHTML=`<div class="a5-meaning-head"><strong>${e(w.headword)}</strong><button class="a5-close" data-a5-meaning-close aria-label="意味を閉じる">×</button></div><p>${e(w.meaning)}</p><p>${e(w.definition)}</p><p>${e(w.context)}</p>${bookmarkButton(w)}`;box.hidden=false;box.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
 function selection(){if(view!=='article')return;const selected=window.getSelection(),body=document.getElementById('a5-body'),panel=document.getElementById('a5-selection');if(!selected||!body||!panel||selected.isCollapsed||!body.contains(selected.anchorNode)||!body.contains(selected.focusNode))return;const startElement=selected.anchorNode.nodeType===1?selected.anchorNode:selected.anchorNode.parentElement,endElement=selected.focusNode.nodeType===1?selected.focusNode:selected.focusNode.parentElement;if(!startElement.closest('[data-a5-paragraph]')||!endElement.closest('[data-a5-paragraph]'))return;const range=selected.getRangeAt(0),contents=range.cloneContents();if(contents.querySelector?.('.a7-translation,.a7-translation-button'))return;const text=selected.toString().trim();if(!text||text.length>120||!/[a-z]/i.test(text))return;const node=selected.anchorNode.nodeType===1?selected.anchorNode:selected.anchorNode.parentElement;const p=node.closest('[data-a5-paragraph]');state.selection={en:text,example:p?.textContent||''};document.getElementById('a5-selection-text').textContent=text;panel.hidden=false}
 function selectDialog(){if(!state.selection)return;document.getElementById('a5-save-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='a5-save-dialog';dialog.className='a5-dialog';dialog.innerHTML=`<form><h2>表現を保存</h2><label>英語<input name="en" maxlength="120" required value="${e(state.selection.en)}"></label><label>日本語の意味（任意）<input name="ja" maxlength="300"></label><label>英語の意味（任意）<input name="def" maxlength="500"></label><div class="a5-dialog-actions"><button type="button" class="a5-secondary" data-a5-dialog-close>閉じる</button><button type="submit" class="a5-secondary">保存する</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-a5-dialog-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target),en=String(data.get('en')).trim();if(!en)return;try{if(!window.AppUI?.saveSelectedExpression)throw Error();const result=window.AppUI.saveSelectedExpression({en,ja:String(data.get('ja')).trim(),def:String(data.get('def')).trim(),example:state.selection.example});if(result===false)throw Error('save rejected');dialog.close();toast('単語・表現に保存しました')}catch{toast('保存できませんでした')}};dialog.addEventListener('close',()=>dialog.remove());dialog.showModal()}
 document.addEventListener('click',event=>{const browseButton=event.target.closest('[data-ab-top],[data-ab-all],[data-ab-shelf],[data-ab-search-toggle]');if(browseButton){if(browseButton.hasAttribute('data-ab-search-toggle')){searchOpen=!searchOpen;rerender();if(searchOpen)document.querySelector('[data-ab-search]')?.focus();return;}if(browseButton.hasAttribute('data-ab-top')){searchOpen=false;return updateBrowse({});}if(browseButton.hasAttribute('data-ab-all'))return updateBrowse({list:true});if(browseButton.hasAttribute('data-ab-shelf'))return updateBrowse({category:browseButton.dataset.abShelf});}if(event.target.closest('a[href]'))return;const b=event.target.closest('[data-a7-level],[data-a7-translation],[data-a7-retry],[data-a5-source-toggle],[data-a5-open],[data-a5-filter],[data-a5-list],[data-a5-save],[data-a5-word],[data-a5-quiz],[data-a5-answer],[data-a5-read],[data-a5-meaning-close],[data-a5-selection-save],[data-a5-selection-close]');if(!b)return;
  if(b.hasAttribute('data-a7-level')){state.level=b.dataset.a7Level;return rerender()}
  if(b.hasAttribute('data-a7-retry'))return open(state.selected);
  if(b.hasAttribute('data-a7-translation')){const id=b.dataset.a7Translation;if(state.allTranslations){state.allTranslations=false;state.translations=new Set(current()?.paragraphs.map(p=>p.id)||[])}if(state.translations.has(id))state.translations.delete(id);else state.translations.add(id);return rerender()}
  if(b.hasAttribute('data-a5-source-toggle')){const box=document.getElementById('a5-source-details');box.hidden=!box.hidden;b.setAttribute('aria-expanded',String(!box.hidden));b.textContent=box.hidden?'詳細':'閉じる';return}
  if(b.hasAttribute('data-a5-open'))return open(b.dataset.a5Open);
  if(b.hasAttribute('data-a5-filter')){state.category=b.dataset.a5Filter;return rerender()}
  if(b.hasAttribute('data-a5-list'))return go('articles');
  if(b.hasAttribute('data-a5-save'))return saveWord(b.dataset.a5Save);
  if(b.hasAttribute('data-a5-word'))return meaning(b.dataset.a5Word);
  if(b.hasAttribute('data-a5-quiz')){const a=current();if(a&&window.QuizUI?.startArticle)window.QuizUI.startArticle(a.id);return}
  if(b.hasAttribute('data-a5-answer')){const a=current(),q=a?.comprehension.find(q=>q.id===b.dataset.a5Answer);if(!q)return;const key=a.id+':'+a.version+':'+q.id;if(state.answers.has(key)||!ordered(a,q).some(c=>c.id===b.dataset.choice))return;if(!saveAnswer(a,q,b.dataset.choice))return;state.answers.set(key,b.dataset.choice);rerender();if(b.dataset.choice!==q.correctChoiceId){const options=document.querySelectorAll?.('[data-a5-answer]')||[];for(const option of options)if(option.dataset.choice===b.dataset.choice){option.classList.add('a5-shake');option.addEventListener('animationend',()=>option.classList.remove('a5-shake'),{once:true})}}return}
  if(b.hasAttribute('data-a5-read')){const a=current();if(!a)return;const values=readStore(READ_KEY);values[a.id]={articleId:a.id,version:a.version,completedAt:new Date().toISOString()};if(writeStore(READ_KEY,values)){rerender();toast('読了にしました')}return}
  if(b.hasAttribute('data-a5-meaning-close')){document.getElementById('a5-meaning').hidden=true;return}
  if(b.hasAttribute('data-a5-selection-close')){document.getElementById('a5-selection').hidden=true;state.selection=null;return}
  if(b.hasAttribute('data-a5-selection-save'))selectDialog();
 });
 document.addEventListener('change',event=>{if(event.target.matches('[data-ab-category]'))return updateBrowse({...browseFilters,q:queryDraft,category:event.target.value,list:false});if(event.target.matches('[data-ab-level]'))return updateBrowse({...browseFilters,q:queryDraft,level:event.target.value,list:false});if(event.target.matches('[data-a7-all-translations]')){state.allTranslations=event.target.checked;state.translations.clear();rerender()}});
 function queueSearch(value,isComposing=false){queryDraft=value;clearTimeout(searchTimer);if(composing||isComposing)return;searchTimer=setTimeout(()=>{if(view==='articles')updateBrowse({...browseFilters,q:queryDraft,list:false},true);},300);}
 document.addEventListener('compositionstart',event=>{if(event.target.matches('[data-ab-search]')){composing=true;clearTimeout(searchTimer);}});
 document.addEventListener('compositionend',event=>{if(event.target.matches('[data-ab-search]')){composing=false;queueSearch(event.target.value);}});
 document.addEventListener('input',event=>{if(event.target.matches('[data-ab-search]')){queueSearch(event.target.value,event.isComposing);return;}if(!event.target.matches('[data-a5-opinion]'))return;const a=current();if(!a)return;const values=readStore(DRAFT_KEY);values[a.id]={articleId:a.id,version:a.version,text:event.target.value,updatedAt:new Date().toISOString()};const ok=writeStore(DRAFT_KEY,values);document.getElementById('a5-draft-status').textContent=ok?'この端末に下書きを保存しました':'保存できませんでした'});
 document.addEventListener('keydown',event=>{const card=event.target;if(card.matches('[role="link"][data-a5-open]')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();open(card.dataset.a5Open)}});
 document.addEventListener('mouseup',selection);document.addEventListener('touchend',()=>setTimeout(selection,50));document.addEventListener('keyup',selection);
 articles=list;article=detail;if(new URL(location.href).searchParams.get('view')==='articles'||browseFilters.category||browseFilters.level||browseFilters.q||browseFilters.list)go('articles');
 window.ArticleUI={open,articles:list,article:detail,scopeChanged:()=>{state.epoch++;state.selected=null;state.loaded=null;state.loading=false;state.loadError=false;state.translations.clear();state.allTranslations=false;state.orders.clear();state.answers.clear();state.selection=null;state.activeWord=null;state.readSession=crypto.randomUUID();document.getElementById('a5-meaning')?.setAttribute('hidden','');document.getElementById('a5-selection')?.setAttribute('hidden','');},readKeys:{read:READ_KEY,opinion:DRAFT_KEY,answers:ANSWER_KEY}};
 Promise.resolve(window.MaterialCatalog?.ready).then(()=>{if(view==='articles'||view==='article')render()}).catch(()=>{if(view==='articles')render()});
})();
