(function(){
 'use strict';
 const quizStore=QuizUI.getStore();
 let appState=null;
 const storage=window.AppStorage||localStorage;
 try{appState=new LearningState.AppState(storage,C1_UNIT_01,DEVELOPMENT_VOCABULARY.items);}catch(e){toast('保存情報を読み込めませんでした');}
 const allItems=[...C1_UNIT_01.items,...DEVELOPMENT_VOCABULARY.items];
 const baseWords=words.map(word=>({...word,bookmarked:false}));
 const personIcon='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></svg>';
 const arrow=()=>'<span class="action-chevron" aria-hidden="true">›</span>';
 let vocabularyTab='saved',vocabularyLevel='C1',detailItem=null;
 nav.splice(0,nav.length,['home','ホーム'],['vocab','単語'],['articles','記事'],['listen','リスニング'],['records','記録']);
 if(appState){for(const index of appState.articleSaves)if(words[index])words[index].bookmarked=true;for(const word of appState.customWords)if(!words.some(x=>x.en===word.en&&x.ja===word.ja))words.push({...word});}
 function savedWords(){return appState?appState.savedVocabulary(quizStore?.bookmarks||[],words):[];}
 function savedIds(){return savedWords().filter(x=>x.id).map(x=>x.id);}
 function vocabularyView(){return EnglishVocabulary.createView(savedWords(),reviewItems(),item=>appState&&quizStore?appState.wordStatus(item.id,quizStore.logs,quizStore.settings.mode):'未学習');}
 function status(item){return vocabularyView().status(item);}
 const gauge=state=>{const filled=state==='定着'?3:state==='学習中'?1:0;return `<span class="proficiency-gauge" role="img" aria-label="${esc(state)}">${[0,1,2].map(index=>`<span class="proficiency-dot ${index<filled?'filled':''}" aria-hidden="true"></span>`).join('')}</span>`;};
 vocabulary=function(){
  const tabs=`<div class="vocabulary-tabs" role="tablist" aria-label="単語教材">${[['saved','保存した語'],['units','上級語彙集']].map(([key,label])=>`<button role="tab" aria-selected="${vocabularyTab===key}" onclick="AppUI.vocabularyTab('${key}')">${label}</button>`).join('')}</div>`;
  let content;
  if(vocabularyTab==='saved'){const sections=vocabularyView().sections(),entries=sections.flatMap(section=>section.items);content=sections.map(section=>`<section class="vocabulary-section" aria-labelledby="vocabulary-${section.state}"><h2 id="vocabulary-${section.state}">${section.state} <span>${section.items.length}</span></h2><div class="vocabulary-group">${section.items.map(item=>`<button class="vocabulary-row" onclick="AppUI.savedDetail(${entries.indexOf(item)})"><span class="vocabulary-label"><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span>${gauge(section.state)}${arrow()}</button>`).join('')}</div></section>${section.state==='復習予定'?`<div class="vocabulary-actions"><button class="primary full" onclick="startReview()">復習をはじめる ${arrow()}</button></div>`:''}`).join('')||'<p class="vocabulary-empty">保存した語はありません</p>';
  }else{const units=(window.MaterialCatalog?.units?.()||[C1_UNIT_01]).filter(unit=>unit.level===vocabularyLevel);content=`<div class="level-switch" role="tablist" aria-label="語彙レベル">${['C1','C2'].map(level=>`<button role="tab" aria-selected="${vocabularyLevel===level}" onclick="AppUI.vocabularyLevel('${level}')">${level}</button>`).join('')}</div>${units.length?`<div class="vocabulary-group">${units.map(unit=>{const best=appState&&quizStore?appState.best(quizStore.settings.mode,unit):null;return `<button class="vocabulary-row unit-row" onclick="QuizUI.startUnit('${esc(unit.id)}')"><span class="unit-number">${['①','②','③','④','⑤'][unit.unitNumber-1]||unit.unitNumber}</span><span class="vocabulary-label"><strong>${esc(unit.title)}</strong></span><span class="unit-score">ベスト ${best??0}/10</span>${best===10?'<span class="unit-clear" role="img" aria-label="クリア">✓</span>':''}${arrow()}</button>`;}).join('')}</div>`:'<p class="vocabulary-empty">教材はありません</p>'}`;}

  return `<div class="sectionhead"><h1>単語・表現</h1>${vocabularyTab==='saved'?'<button class="textbtn" onclick="addWord()">＋ 追加</button>':''}</div>${tabs}${content}`;
 };
 wordDetail=function(){const item=detailItem||savedWords().find(x=>x.headword.toLowerCase()===words[selectedWord]?.en.toLowerCase());if(!item)return '<button class="textbtn" onclick="go(\'vocab\')">単語・表現へ ›</button>';const state=status(item);return `<button class="back" onclick="go('vocab')">単語・表現へ ${arrow()}</button><p class="vocabulary-detail-state">${state}</p><div class="flash"><strong>${esc(item.headword)}</strong><p>${esc(item.meaning)}</p></div><div class="wordmeaning"><h3>${esc(item.definition||'')}</h3><p>${esc(item.example||'')}</p></div>${item.id?`<button class="primary full" onclick="QuizUI.startWord('${item.id}')">この表現を練習する ${arrow()}</button>`:''}`;};
 function reviewItems(){return appState&&quizStore?appState.reviewCandidates(quizStore.logs,savedIds(),quizStore.settings.mode).filter(EnglishQuiz.validateItem):[];}
 home=function(){
  const count=reviewItems().length,date=new Date(),dateText=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'long'}).format(date),hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'numeric',hourCycle:'h23'}).format(date)),greeting=hour<11?'おはようございます':hour<18?'こんにちは':'こんばんは';
  const best=quizStore&&appState?appState.best(quizStore.settings.mode):null,last=appState?.lastUnit,modeText=quizStore?.settings.mode==='en'?'英語 → 英語':'英語 → 日本語';
  const articles=lessons.map((lesson,index)=>({lesson,index})).filter(({lesson})=>lesson.status==='checked'&&lesson.publishedAt&&Number.isFinite(Date.parse(lesson.publishedAt))&&Date.parse(lesson.publishedAt)<=Date.now()).sort((a,b)=>Date.parse(b.lesson.publishedAt)-Date.parse(a.lesson.publishedAt)).slice(0,3);
  return `<div class="home-greeting"><small>${esc(dateText)} · ${greeting}</small><h1>今日の学習</h1></div><section class="home-review" aria-labelledby="home-review-title"><div class="home-review-label" id="home-review-title">今日の復習</div>${count?`<div class="home-review-count"><strong>${count}</strong><span>語</span></div><p class="home-review-caption">${modeText}で復習</p>`:'<div class="home-review-complete"><span aria-hidden="true">✓</span><h2>今日の復習は完了</h2></div>'}${quizStore&&appState?`<button class="home-primary" onclick="${count?'startReview()':'QuizUI.startUnit()'}">${count?'復習をはじめる':'C1①から10問'} ${arrow()}</button>`:''}</section>${last&&last.unitId===C1_UNIT_01.id?`<section class="home-section"><div class="home-section-head"><h2>続きから</h2></div><button class="home-resume-row" onclick="QuizUI.startUnit()"><span><strong>C1①${best===null?'':' · ベスト '+best+'/10'}</strong><small>${modeText} · ${best===10?'クリア':best===null?'未完了':'もう一度挑戦する'}</small></span>${arrow()}</button></section>`:''}${articles.length?`<section class="home-section"><div class="home-section-head"><h2>新着記事</h2></div>${articles.map(({lesson,index})=>{const minutes=lesson.readingMinutes||Math.max(1,Math.ceil(lesson.text.join(' ').split(/\s+/).length/200));return `<button class="home-article-row" onclick="lessonOpen(${index})"><label>${esc(lesson.genre)}</label><h3>${esc(lesson.title)}</h3><small>約${minutes}分</small></button>`;}).join('')}</section>`:''}<section class="home-section"><div class="home-section-head"><h2>表現ノート</h2></div><button class="home-note-row" onclick="AppUI.showSaved()"><span><strong>保存した語 ${savedWords().length}件</strong><small>一覧を見る</small></span>${arrow()}</button></section>`;
 };
 let accountSyncCleanup=null;const account=document.createElement('dialog');account.id='app-settings';document.body.append(account);
 function openSettings(){window.AccountSync?.openAccount();}
 account.addEventListener('close',()=>{accountSyncCleanup?.();accountSyncCleanup=null;});
 account.addEventListener('click',e=>{if(e.target===account){const box=account.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)account.close();}});
 function openNotes(){const entries=savedWords();account.innerHTML=`<div class="settings-sheet"><div class="settings-header"><h2>表現ノート</h2><button aria-label="表現ノートを閉じる" onclick="AppUI.closeSettings()">×</button></div>${entries.length?entries.map(item=>item.id?`<button class="home-resume-row" onclick="AppUI.openSaved('${item.id}')"><span><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span>${arrow()}</button>`:`<div class="home-resume-row"><span><strong>${esc(item.headword)}</strong><small>${esc(item.meaning)}</small></span></div>`).join(''):'<p class="muted">保存した語はありません</p>'}</div>`;account.showModal();}
 function openCredits(){window.AccountSync?.openAbout();}
 const originalSave=saveArticleWord;
 saveArticleWord=function(){try{if(!appState)throw Error('storage');const index=lessons[selectedArticle].word,item=allItems.find(x=>x.headword.toLowerCase()===words[index].en.toLowerCase());appState.setSavedState(quizStore,item?[...quizStore.bookmarks,item.id]:quizStore.bookmarks,[...appState.articleSaves,index],EnglishQuiz.KEYS.bookmarks);originalSave();}catch(e){toast('保存できませんでした');}};
 const originalAdd=addWord;
 addWord=function(){if(!appState){toast('保存できませんでした');return;}const count=words.length;originalAdd();if(words.length>count&&appState){try{appState.addCustomWord(words[words.length-1]);render();}catch(e){words.splice(count);render();toast('保存できませんでした');}}};
 const originalRender=render;
 render=function(){originalRender();document.body.dataset.view=view;
  const active=view==='word'||view==='quiz'?'vocab':view==='article'?'articles':view;
  const links=nav.map(([page,label])=>`<button class="navbtn ${active===page?'active':''}" onclick="go('${page}')" ${active===page?'aria-current="page"':''}>${ico(page)}<span>${label}</span></button>`).join('');
  document.getElementById('nav').innerHTML=links;document.querySelector('.side-links').innerHTML=links;
  document.querySelectorAll('#app .meta,#app .eyebrow').forEach(el=>{el.textContent=el.textContent.replace(/\s*·\s*B2[–〜~-]C1/g,'');});
  document.querySelectorAll('#app button').forEach(button=>{const walker=document.createTreeWalker(button,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))node.textContent=node.textContent.replace(/→(?=\s*$)|←/g,'›');});
 };
 document.querySelector('header').className='app-header';document.querySelector('header').innerHTML=`<div class="brand">English Notes</div><button class="account-button" aria-label="アカウント設定" onclick="AppUI.openSettings()">${personIcon}</button>`;
 const side=document.createElement('aside');side.className='side-nav';side.innerHTML=`<div class="side-brand">English Notes</div><nav class="side-links" aria-label="メインメニュー"></nav><button class="side-account" onclick="AppUI.openSettings()">${personIcon}<span>アカウント</span></button>`;document.body.prepend(side);
 window.AppUI={addCatalog:items=>{for(const item of items){const index=allItems.findIndex(x=>x.id===item.id);if(index<0)allItems.push(item);else allItems[index]=item;if(appState){const stored=appState.items.findIndex(x=>x.id===item.id);if(stored<0)appState.items.push(item);else appState.items[stored]=item;}}},saveMaterialWord:item=>{if(!appState||!quizStore)return false;if(!allItems.some(x=>x.id===item.id)){allItems.push(item);appState.items.push(item);}appState.setSavedState(quizStore,[...quizStore.bookmarks,item.id],appState.articleSaves,EnglishQuiz.KEYS.bookmarks);return true;},saveSelectedExpression:word=>{if(!appState)return false;const existing=words.find(x=>x.en.trim().toLowerCase()===word.en.trim().toLowerCase());const next={...word,bookmarked:true};appState.addCustomWord(next);if(existing)Object.assign(existing,next);else words.push(next);return true;},vocabularyTab:tab=>{vocabularyTab=tab;render();},vocabularyLevel:level=>{vocabularyLevel=level;render();},savedDetail:index=>{detailItem=vocabularyView().sections().flatMap(section=>section.items)[index];go('word');},showSaved:()=>{vocabularyTab='saved';go('vocab');},showCredits:()=>window.AccountSync?.openAbout(),reviewItems,openSettings,openCredits,closeSettings:()=>account.close(),openNotes,openSaved:id=>{account.close();detailItem=savedWords().find(x=>x.id===id);if(detailItem)go('word');},unitStarted:unit=>{try{appState.startUnit(quizStore.settings.mode,unit||C1_UNIT_01);return true;}catch(e){toast('学習履歴を保存できませんでした');return false;}},isSaved:id=>savedIds().includes(id),toggleBookmark:id=>{const removing=savedIds().includes(id),item=allItems.find(x=>x.id===id),indexes=words.map((w,i)=>({w,i})).filter(({w})=>item&&w.en.toLowerCase()===item.headword.toLowerCase()).map(({i})=>i);appState.setSavedState(quizStore,removing?quizStore.bookmarks.filter(x=>x!==id):[...quizStore.bookmarks,id],removing?appState.articleSaves.filter(i=>!indexes.includes(i)):appState.articleSaves,EnglishQuiz.KEYS.bookmarks,removing&&item?[...appState.unsavedCustomWords,item.headword.trim().toLowerCase()]:appState.unsavedCustomWords);if(removing)for(const i of indexes)words[i].bookmarked=false;},unitCompleted:(session,unit)=>{try{if(!appState.sessions.some(x=>x.sessionId===session.id))appState.completeUnit(session,unit||C1_UNIT_01);return true;}catch(e){return false;}}};
 window.AppUI.syncCatalog=()=>({items:[...allItems],legacyWords:baseWords.map(word=>({...word}))});
 window.AppUI.reloadData=({scopeChanged=false}={})=>{
  appState=new LearningState.AppState(storage,C1_UNIT_01,DEVELOPMENT_VOCABULARY.items);appState.items=[...allItems];
  words.splice(0,words.length,...baseWords.map(word=>({...word})));
  for(const index of appState.articleSaves)if(words[index])words[index].bookmarked=true;
  for(const word of appState.customWords)if(!words.some(x=>x.en===word.en&&x.ja===word.ja))words.push({...word});
  if(scopeChanged)detailItem=null;
 };
 window.AppUI.learningSettings=()=>({...quizStore.settings});
 window.AppUI.saveLearningSettings=patch=>{quizStore.setSettings(patch);render();};
 window.AppUI.creditMarkup=()=>`<h3>教材の出典</h3><h3>CEFR-J Wordlist v1.5</h3><p>Compiled by Yukio Tono · Tono Laboratory, Tokyo University of Foreign Studies</p><p>記事の語彙レベル検証に使用しています。</p><p><a href="https://github.com/openlanguageprofiles/olp-en-cefrj" target="_blank" rel="noopener noreferrer">語彙リスト・利用条件</a></p><h3>Octanove Vocabulary Profile C1/C2 v1.0</h3><p>Octanove Labs</p><p><a href="https://github.com/openlanguageprofiles/olp-en-cefrj" target="_blank" rel="noopener noreferrer">語彙リスト・利用条件</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a></p><p>CEFR-J／Octanove Vocabulary Profileのレベル付けに基づく目安</p><p>語を抽出し独自の順序で構成。意味・定義・例文・選択肢・解説は本アプリ向けに作成しています。C1①の教材データはCC BY-SA 4.0で提供します。</p><h3>記事・写真</h3><p>記事の原文リンクと写真の撮影者・利用元は、各記事の出典詳細と写真の下に表示しています。</p><p><a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Unsplashの利用条件</a></p>`;
 const materialUnavailable=()=>Boolean(window.MaterialCatalog?.hydrating?.()||window.MaterialCatalog?.error?.());
 const homeWithMaterials=home;
 home=function(){const html=homeWithMaterials();if(!materialUnavailable())return html;const failed=Boolean(window.MaterialCatalog?.error?.());return html.replace(/<section class="home-review"[\s\S]*?<\/section>/,`<section class="home-review" aria-labelledby="home-review-title"><div class="home-review-label" id="home-review-title">今日の復習</div><p role="${failed?'alert':'status'}">${failed?'復習対象を読み込めませんでした':'復習対象を読み込んでいます'}</p>${failed?'<button class="home-primary" onclick="MaterialCatalog.hydrateSaved()">再試行</button>':''}</section>`).replace(/保存した語 \d+件/g,'保存した語');};
 const vocabularyWithMaterials=vocabulary;
 vocabulary=function(){const html=vocabularyWithMaterials();if(vocabularyTab!=='saved'||!materialUnavailable())return html;const end=html.indexOf('</div>',html.indexOf('class="vocabulary-tabs"'))+6,failed=Boolean(window.MaterialCatalog?.error?.());return html.slice(0,end)+`<p class="vocabulary-empty" role="${failed?'alert':'status'}">${failed?'保存した語を読み込めませんでした':'保存した語を読み込んでいます'}</p>${failed?'<button class="a5-secondary" onclick="MaterialCatalog.hydrateSaved()">再試行</button>':''}`;};
 const theme=document.querySelector('meta[name="theme-color"]');if(theme)theme.content=getComputedStyle(document.documentElement).getPropertyValue('--color-bg').trim();
 render();
})();
