(function(){
 'use strict';
 const READ_KEY='english-notes.article.read.v1',DRAFT_KEY='english-notes.article.opinion.v1',ANSWER_KEY='english-notes.article.answers.v1';
 const state={category:'すべて',selected:null,orders:new Map(),answers:new Map(),selection:null,activeWord:null};
 function saveAnswer(a,q,choiceId){const events=readStore(ANSWER_KEY),eventId=crypto.randomUUID();events[eventId]={eventId,questionId:q.id,articleId:a.id,wordId:null,materialVersion:a.version,selectedChoiceId:choiceId,correctChoiceId:q.correctChoiceId,correct:choiceId===q.correctChoiceId,skipped:false,answeredAt:new Date().toISOString(),kind:'comprehension',mode:'en',sessionId:state.readSession};return writeStore(ANSWER_KEY,events)}
 const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safeUrl=value=>{try{const u=new URL(value,location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
 const readStore=key=>{try{const val=JSON.parse(localStorage.getItem(key)||'{}');return val&&typeof val==='object'&&!Array.isArray(val)?val:{}}catch{return {}}};
 function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('保存できませんでした');return false}}
 const catalogue=()=>window.MaterialCatalog?.articles?.()||[];
 const current=()=>catalogue().find(a=>a.id===state.selected)||null;
 const read=a=>Boolean(readStore(READ_KEY)[a.id]?.completedAt);
 const saved=w=>Boolean(window.AppUI?.isSaved?.(w.id));
 function published(value){const timestamp=Date.parse(value);if(!Number.isFinite(timestamp))return '';const days=Math.floor((Date.now()-timestamp)/86400000);if(days<1)return '今日公開';if(days<7)return days+'日前に公開';return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'numeric',day:'numeric'}).format(new Date(timestamp))+' 公開'}
 function meta(a){return `<div class="a5-meta"><span>${e(a.category)}</span><span>${e(a.level)}</span><span>約${e(a.readingMinutes)}分</span><span>${e(published(a.publishedAt))}</span></div>`}
 function photo(a){const p=a.photo;if(!p?.assetPath)return '<div class="a5-photo-fallback" aria-hidden="true">'+ico('articles')+'</div>';const url=safeUrl(p.pageUrl);return `<figure class="a5-photo"><img src="${e(p.assetPath)}" alt="${e(p.alt)}" loading="lazy"><figcaption>${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(p.credit)}</a>`:e(p.credit)}</figcaption></figure>`}
 function status(a){return read(a)?'<span class="a5-read-status"><span aria-hidden="true">✓</span>読了</span>':''}
 function open(id){if(!catalogue().some(a=>a.id===id)){toast('記事を読み込めませんでした');return}state.selected=id;state.readSession=crypto.randomUUID();state.activeWord=null;state.selection=null;state.orders.clear();state.answers.clear();go('article')}
 function list(){const all=[...catalogue()].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)),categories=['すべて','仕事','教養','日常・文化'];if(!categories.includes(state.category))state.category='すべて';const entries=all.filter(a=>state.category==='すべて'||a.category===state.category),first=entries[0];return `<h1>記事</h1><div class="a5-filters" aria-label="記事のジャンル">${categories.map(c=>`<button class="a5-secondary" data-a5-filter="${e(c)}" aria-pressed="${state.category===c}">${e(c)}</button>`).join('')}</div>${first?`<section class="a5-feature" data-a5-open="${e(first.id)}" role="link" tabindex="0" aria-label="${e(first.title)}">${photo(first)}<div>${meta(first)}<button class="a5-titlelink" data-a5-open="${e(first.id)}"><h2>${e(first.title)}</h2></button><p class="a5-summary">${e(first.summaryJa)}</p>${status(first)}</div></section><div class="a5-grid">${entries.slice(1).map(a=>`<article class="a5-card" data-a5-open="${e(a.id)}" role="link" tabindex="0" aria-label="${e(a.title)}">${photo(a)}${meta(a)}<button class="a5-titlelink" data-a5-open="${e(a.id)}"><h2>${e(a.title)}</h2></button><p class="a5-summary">${e(a.summaryJa)}</p>${status(a)}</article>`).join('')}</div>`:'<p class="a5-empty">公開された記事はありません</p>'}`}
 function sources(a){return `<section class="a5-source"><h2>出典・原文</h2><p>${e(a.editorialNotice)}</p><ul>${(a.sources||[]).map(s=>`<li><a href="${e(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${e(s.title)}</a><p>${e(s.publisher)}${s.author?' · '+e(s.author):''}${s.authors?.length?' · '+e(s.authors.join(', ')):''} · ${e(s.dateKind==='inscription-year'?'登録年 '+s.publishedAt:s.publishedAt)}${s.dateNote?' · '+e(s.dateNote):''}<br>出典確認日 ${e(s.checkedAt)}</p></li>`).join('')}</ul></section>`}
 function paragraphs(a){return (a.paragraphs||[]).map(p=>{const words=(a.vocabulary||[]).filter(w=>w.contextParagraphId===p.id);let parts=[{text:p.text}];for(const w of words){const form=w.surfaceForm||w.headword;if(!form)continue;const pattern=new RegExp('\\b'+form.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','ig');parts=parts.flatMap(part=>{if(part.word)return [part];const result=[];let start=0;for(const match of part.text.matchAll(pattern)){result.push({text:part.text.slice(start,match.index)},{text:match[0],word:w.id});start=match.index+match[0].length}result.push({text:part.text.slice(start)});return result})}return `<p id="a5-${e(p.id)}" data-a5-paragraph="${e(p.id)}">${parts.map(part=>part.word?`<button class="a5-keyword" data-a5-word="${e(part.word)}">${e(part.text)}</button>`:e(part.text)).join('')}</p>`}).join('')}
 function wordBlock(a){return `<section class="a5-section"><h2>この記事の単語・表現</h2><div class="a5-vocab">${(a.vocabulary||[]).map(w=>`<div class="a5-wordrow"><div><strong>${e(w.headword)}</strong><p>${e(w.meaning)}</p><p class="a5-example">${e(w.example)}</p></div><button class="a5-secondary" data-a5-save="${e(w.id)}">${saved(w)?'保存済み ✓':'保存する'}</button></div>`).join('')}</div>${a.vocabulary?.length?'<button class="a5-secondary a5-quiz-entry" data-a5-quiz>この記事の単語をクイズで復習</button>':''}</section>`}
 function ordered(a,q){const key=a.id+':'+a.version+':'+q.id;if(!state.orders.has(key)){let options;if(window.EnglishQuiz?.shuffleChoices)options=window.EnglishQuiz.shuffleChoices(q);else{options=q.choices.map((text,i)=>({id:q.choiceIds[i],text}));for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}}state.orders.set(key,options)}return state.orders.get(key)}
 function questions(a){return `<section class="a5-section"><h2>内容を確認する</h2>${(a.comprehension||[]).map((q,n)=>{const key=a.id+':'+a.version+':'+q.id,chosen=state.answers.get(key),done=chosen!==undefined;return `<section class="a5-question"><h3>${n+1}. ${e(q.question)}</h3><div class="a5-options">${ordered(a,q).map((choice,i)=>`<button class="a5-secondary a5-option ${done?(choice.id===q.correctChoiceId?'correct':choice.id===chosen?'wrong':''):''}" data-a5-answer="${e(q.id)}" data-choice="${e(choice.id)}" ${done?'disabled':''}><small>${i+1}</small><span>${e(choice.text)}</span>${done&&choice.id===q.correctChoiceId?'<span aria-label="正解">✓</span>':done&&choice.id===chosen?'<span aria-label="誤答">×</span>':''}</button>`).join('')}</div>${done?`<div class="a5-evidence" role="status"><strong>${chosen===q.correctChoiceId?'正解です':'正解を確認しましょう'}</strong><p>${e(q.explanationJa)}</p>${(q.evidenceParagraphIds||[]).map(id=>{const p=a.paragraphs.find(p=>p.id===id);return p?`<blockquote><a href="#a5-${e(id)}">本文 ${e(id.toUpperCase())}</a><br>${e(p.text)}</blockquote>`:''}).join('')}</div>`:''}</section>`}).join('')}</section>`}
 function detail(){const a=current();if(!a)return '<button class="back" data-a5-list>← 記事</button><p class="a5-empty">記事を選択してください</p>';const draft=readStore(DRAFT_KEY)[a.id]?.text||'';return `<button class="back" data-a5-list>← 記事</button>${photo(a)}<div class="a5-heading">${meta(a)}<h1>${e(a.title)}</h1><p class="a5-summary">${e(a.summaryJa)}</p></div>${sources(a)}${wordBlock(a)}<section class="a5-section"><h2>本文</h2><div id="a5-meaning" class="a5-meaning" hidden></div><div class="a5-body" id="a5-body" tabindex="0" aria-label="英文本文、文字を選択して表現を保存">${paragraphs(a)}</div><div class="a5-selection" id="a5-selection" hidden><span id="a5-selection-text"></span><button class="a5-secondary" data-a5-selection-save>選んだ表現を保存</button><button class="a5-close" data-a5-selection-close aria-label="選択を閉じる">×</button></div></section>${questions(a)}${a.opinion?`<section class="a5-section a5-opinion"><h2>自分の意見を書く（任意）</h2><label class="a5-opinion-label" for="a5-opinion">${e(a.opinion.prompt)}</label><textarea id="a5-opinion" data-a5-opinion placeholder="英語で自分の考えを書く">${e(draft)}</textarea><p class="a5-draft-status" id="a5-draft-status">${draft?'この端末に保存した下書き':''}</p></section>`:''}<button class="primary a5-mark-read" data-a5-read>${read(a)?'読了済み ✓':'読了にする'}</button>`}
 function rerender(){const scroll=window.scrollY;render();window.scrollTo(0,scroll)}
 function word(id){return current()?.vocabulary?.find(w=>w.id===id)}
 function saveWord(id){const w=word(id);if(!w)return;try{if(!window.AppUI?.saveMaterialWord)throw Error('save hook unavailable');const result=window.AppUI.saveMaterialWord(w);if(result===false)throw Error('save rejected');document.querySelectorAll('[data-a5-save]').forEach(b=>{if(b.dataset.a5Save===id)b.textContent='保存済み ✓'});toast('単語・表現に保存しました')}catch{toast('保存できませんでした')}}
 function meaning(id){const w=word(id),box=document.getElementById('a5-meaning');if(!w||!box)return;box.innerHTML=`<div class="a5-meaning-head"><strong>${e(w.headword)}</strong><button class="a5-close" data-a5-meaning-close aria-label="意味を閉じる">×</button></div><p>${e(w.meaning)}</p><p>${e(w.definition)}</p><p>${e(w.context)}</p><button class="a5-secondary" data-a5-save="${e(id)}">${saved(w)?'保存済み ✓':'保存する'}</button>`;box.hidden=false;box.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
 function selection(){if(view!=='article')return;const selected=window.getSelection(),body=document.getElementById('a5-body'),panel=document.getElementById('a5-selection');if(!selected||!body||!panel||selected.isCollapsed||!body.contains(selected.anchorNode)||!body.contains(selected.focusNode))return;const text=selected.toString().trim();if(!text||text.length>120||!/[a-z]/i.test(text))return;const node=selected.anchorNode.nodeType===1?selected.anchorNode:selected.anchorNode.parentElement;const p=node.closest('[data-a5-paragraph]');state.selection={en:text,example:p?.textContent||''};document.getElementById('a5-selection-text').textContent=text;panel.hidden=false}
 function selectDialog(){if(!state.selection)return;document.getElementById('a5-save-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='a5-save-dialog';dialog.className='a5-dialog';dialog.innerHTML=`<form><h2>表現を保存</h2><label>英語<input name="en" maxlength="120" required value="${e(state.selection.en)}"></label><label>日本語の意味（任意）<input name="ja" maxlength="300"></label><label>英語の意味（任意）<input name="def" maxlength="500"></label><div class="a5-dialog-actions"><button type="button" class="a5-secondary" data-a5-dialog-close>閉じる</button><button type="submit" class="a5-secondary">保存する</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-a5-dialog-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target),en=String(data.get('en')).trim();if(!en)return;try{if(!window.AppUI?.saveSelectedExpression)throw Error();const result=window.AppUI.saveSelectedExpression({en,ja:String(data.get('ja')).trim(),def:String(data.get('def')).trim(),example:state.selection.example});if(result===false)throw Error('save rejected');dialog.close();toast('単語・表現に保存しました')}catch{toast('保存できませんでした')}};dialog.addEventListener('close',()=>dialog.remove());dialog.showModal()}
 document.addEventListener('click',event=>{if(event.target.closest('a[href]'))return;const b=event.target.closest('[data-a5-open],[data-a5-filter],[data-a5-list],[data-a5-save],[data-a5-word],[data-a5-quiz],[data-a5-answer],[data-a5-read],[data-a5-meaning-close],[data-a5-selection-save],[data-a5-selection-close]');if(!b)return;
  if(b.hasAttribute('data-a5-open'))return open(b.dataset.a5Open);
  if(b.hasAttribute('data-a5-filter')){state.category=b.dataset.a5Filter;return rerender()}
  if(b.hasAttribute('data-a5-list'))return go('articles');
  if(b.hasAttribute('data-a5-save'))return saveWord(b.dataset.a5Save);
  if(b.hasAttribute('data-a5-word'))return meaning(b.dataset.a5Word);
  if(b.hasAttribute('data-a5-quiz')){const a=current();if(a&&window.QuizUI?.startArticle)window.QuizUI.startArticle(a.id);return}
  if(b.hasAttribute('data-a5-answer')){const a=current(),q=a?.comprehension.find(q=>q.id===b.dataset.a5Answer);if(!q)return;const key=a.id+':'+a.version+':'+q.id;if(state.answers.has(key)||!ordered(a,q).some(c=>c.id===b.dataset.choice))return;if(!saveAnswer(a,q,b.dataset.choice))return;state.answers.set(key,b.dataset.choice);rerender();if(b.dataset.choice!==q.correctChoiceId){const options=document.querySelectorAll?.('[data-a5-answer]')||[];for(const option of options)if(option.dataset.choice===b.dataset.choice){option.classList.add('a5-shake');option.addEventListener('animationend',()=>option.classList.remove('a5-shake'),{once:true})}}return}
  if(b.hasAttribute('data-a5-read')){const a=current();if(!a)return;const values=readStore(READ_KEY);values[a.id]={articleId:a.id,version:a.version,completedAt:new Date().toISOString()};if(writeStore(READ_KEY,values)){rerender();toast('読了にしました')}return}
  if(b.hasAttribute('data-a5-meaning-close')){document.getElementById('a5-meaning').hidden=true;return}
  if(b.hasAttribute('data-a5-selection-close')){document.getElementById('a5-selection').hidden=true;state.selection=null;return}
  if(b.hasAttribute('data-a5-selection-save'))selectDialog();
 });
 document.addEventListener('input',event=>{if(!event.target.matches('[data-a5-opinion]'))return;const a=current();if(!a)return;const values=readStore(DRAFT_KEY);values[a.id]={articleId:a.id,version:a.version,text:event.target.value,updatedAt:new Date().toISOString()};const ok=writeStore(DRAFT_KEY,values);document.getElementById('a5-draft-status').textContent=ok?'この端末に下書きを保存しました':'保存できませんでした'});
 document.addEventListener('keydown',event=>{const card=event.target;if(card.matches('[role="link"][data-a5-open]')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();open(card.dataset.a5Open)}});
 document.addEventListener('mouseup',selection);document.addEventListener('touchend',()=>setTimeout(selection,50));document.addEventListener('keyup',selection);
 articles=list;article=detail;
 window.ArticleUI={open,articles:list,article:detail,readKeys:{read:READ_KEY,opinion:DRAFT_KEY,answers:ANSWER_KEY}};
 Promise.resolve(window.MaterialCatalog?.ready).then(()=>{if(view==='articles'||view==='article')render()}).catch(()=>{if(view==='articles')render()});
})();
