const test=require('node:test'),assert=require('node:assert/strict');const {validateLevel,levelFor}=require('../scripts/article-level-validation.cjs');
function article(){const text=Array(30).fill('People work and learn in a school.').join(' ');return{id:'new-test',level:'A2',createdAt:'2026-10-05',paragraphs:[{id:'p1',text,translationJa:'人々は学校で仕事をし学びます。'}],sources:[{publishedAt:'2026-10-02'}],comprehension:[{type:'inference'}],vocabularyReview:{status:'reviewed',reason:'Content checked'}};}
test('source freshness uses creation date and not the current date',()=>{const a=article();let r=validateLevel(a);assert.equal(r.stats.sourceAgeDays,3);assert.ok(!r.errors.some(x=>x.includes('days old')));a.sources[0].publishedAt='2026-09-01';assert.ok(validateLevel(a).errors.some(x=>x.includes('days old')));});
test('translations and numeric correspondence are validated',()=>{const a=article();a.paragraphs[0].text+=' 17 communities.';assert.ok(validateLevel(a).errors.some(x=>x.includes('number 17')));a.paragraphs[0].translationJa+='17の地域';assert.ok(!validateLevel(a).errors.some(x=>x.includes('number 17')));a.paragraphs[0].translationJa='';assert.ok(validateLevel(a).errors.some(x=>x.includes('translation required')));});
test('unlisted words remain unknown and require documented review',()=>{const a=article();a.paragraphs[0].text+=' '+Array(30).fill('unlistedxyz').join(' ');delete a.vocabularyReview;const r=validateLevel(a);assert.ok(r.stats.unknownWords.unlistedxyz);assert.ok(r.errors.some(x=>x.includes('documented content review')));});
test('basic inflections and irregular forms resolve to the list level',()=>{assert.equal(levelFor('children'),levelFor('child'));assert.equal(levelFor('worked'),levelFor('work'));assert.equal(levelFor('is'),levelFor('be'));assert.equal(levelFor('unlistedxyz'),null);});
test('entity aliases validate the Japanese paragraph containing the proper name',()=>{const a=article();a.paragraphs[0].text+=' Samoa has 17 places.';a.paragraphs[0].translationJa+='サモアには17地域あります。';a.validationEntityAliases={Samoa:'サモア'};assert.ok(!validateLevel(a).errors.some(x=>x.includes('entity Samoa')));a.validationEntityAliases.Samoa='サモア諸島';assert.ok(validateLevel(a).errors.some(x=>x.includes('entity Samoa')));});
test('proper-name phrase exclusions do not exclude common components elsewhere',()=>{const a=article();a.paragraphs[0].text+=' Tsunami Ready is a name. A tsunami can come.';a.validationProperNouns=['Tsunami Ready'];const r=validateLevel(a);assert.equal(r.stats.unknownWords.tsunami,1);});
test('number matching does not accept a number contained in a different number',()=>{const a=article();a.paragraphs[0].text+=' 17 places.';a.paragraphs[0].translationJa+='117の地域';assert.ok(validateLevel(a).errors.some(x=>x.includes('number 17')));});
