const test=require('node:test');
const assert=require('node:assert/strict');
const {createStorage,KEYS}=require('../app-storage.js');
function memory(){const values=new Map();return {getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)}}
function setup(){const m=memory(),s=createStorage(m);s.setUser('a');s.setItem(KEYS.settings,'{"mode":"en"}');return {m,s,p:s.pending()[0]}}
test('blocked revisions survive restart, protect local data and are excluded from pending',()=>{const {m,s,p}=setup();assert.equal(s.block(p.table,p.key,p.revision,{status:400,code:'23514'}),true);assert.equal(s.pending().length,0);const again=createStorage(m,{userId:'a'});assert.equal(again.blocked().length,1);assert.equal(again.blocked()[0].status,400);again.merge('preferences',[{setting_key:'mode',value:'ja',updated_at:'2099-01-01T00:00:00Z'}]);assert.equal(JSON.parse(again.getItem(KEYS.settings)).mode,'en');assert.equal(again.exportData().blockedData.length,1)});
test('unchanged local data remains blocked; an actual new revision releases it',()=>{const {s,p}=setup();s.block(p.table,p.key,p.revision,{status:422});s.setItem(KEYS.settings,'{"mode":"en"}');assert.equal(s.blocked().length,1);s.setItem(KEYS.settings,'{"mode":"ja"}');assert.equal(s.blocked().length,0);assert.equal(s.pending().length,1);assert.equal(s.block(p.table,p.key,p.revision,{status:400}),false);assert.equal(s.discardBlocked(p.table,p.key,p.revision),false)});
test('discarding blocked transmission preserves local learning data and other namespaces',()=>{const {m,s,p}=setup();s.block(p.table,p.key,p.revision,{status:400});s.setUser('b');assert.equal(s.blocked().length,0);s.setUser('a');assert.equal(s.discardBlocked(p.table,p.key,p.revision),true);assert.equal(s.pending().length,0);assert.equal(JSON.parse(s.getItem(KEYS.settings)).mode,'en');assert.equal(createStorage(m,{userId:'a'}).blocked().length,0)});
test('import snapshots and partial results persist; unchanged retry cannot release blocked revision',()=>{const m=memory(),s=createStorage(m);s.setItem(KEYS.goals,'{"daily":null,"weekly":null}');const guest=s.snapshot();s.setUser('a');const imported=s.importGuest(),p=s.pending()[0];s.block(p.table,p.key,p.revision,{status:400});s.recordImportResult({snapshotId:imported.snapshotId,successful:1,failed:1,tables:{preferences:{successful:1,failed:1}}});s.importGuest();const persisted=createStorage(m,{userId:'a'});assert.deepEqual(persisted.snapshot().migration.pendingGuestImport.snapshot.values,guest.values);assert.deepEqual(persisted.snapshot().migration.pendingGuestImport.snapshot.rows,guest.rows);assert.equal(persisted.snapshot().migration.importResult.failed,1);assert.equal(persisted.blocked().length,1)});
test('successful migration retains pre-import snapshot after guest changes and reload',()=>{const m=memory(),s=createStorage(m);s.setItem(KEYS.settings,'{"mode":"en"}');const guest=s.snapshot();s.setUser('a');const imported=s.importGuest();s.markGuestImported(imported.snapshotId);assert.equal(s.snapshot().migration.pendingGuestImport,undefined);s.setUser(null);s.setItem(KEYS.settings,'{"mode":"ja"}');const again=createStorage(m,{userId:'a'});assert.deepEqual(again.snapshot().migration.importSnapshots[imported.snapshotId].snapshot.rows,guest.rows)});
test('authentication and transient failures cannot enter quarantine',()=>{const {s,p}=setup();for(const status of [401,500,0,undefined])assert.throws(()=>s.block(p.table,p.key,p.revision,{status}),/permanent/);assert.equal(s.pending().length,1)});
