const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'..');
async function load({tamper=false,bookmarks=[],failVocabulary=false}={}){const registered=[],saved=[],requests=[],unit={id:'advanced-vocabulary-c1-01',items:[]};const rawManifest=JSON.parse(fs.readFileSync(path.join(root,'materials/manifest.json'),'utf8'));const files=new Map(),sha=text=>crypto.createHash('sha256').update(text).digest('hex');const refs=rawManifest.materials.map(ref=>({...ref,sha256:sha(fs.readFileSync(path.join(root,ref.path),'utf8'))})),articles=refs.filter(r=>r.kind==='article').map(ref=>{const a=JSON.parse(fs.readFileSync(path.join(root,ref.path),'utf8'));const metadata={id:a.id,version:a.version,publishedAt:a.publishedAt,title:a.title,category:a.category,level:a.level};const sidepath=`materials/article-vocabulary/${path.basename(ref.path)}`,text=JSON.stringify({id:a.id,version:a.version,items:a.vocabulary});files.set(sidepath,text);return{a,metadata,ref:{id:a.id,version:a.version,path:sidepath,sha256:sha(text)}};});const text=JSON.stringify({id:'article-index',version:1,articles:articles.map(x=>x.metadata)});files.set('materials/articles/index.json',text);const manifest={materials:refs,articleIndex:{id:'article-index',version:1,path:'materials/articles/index.json',sha256:sha(text)},articleVocabulary:articles.map(x=>x.ref),wordIndex:Object.fromEntries(articles.flatMap(x=>x.a.vocabulary.map(v=>[v.id,{articleId:x.a.id}])))};files.set('materials/manifest.json',JSON.stringify(manifest));const ctx={TextEncoder,Date,crypto:crypto.webcrypto,C1_UNIT_01:unit,document:{body:{classList:{contains:()=>false}}},render(){},console:{error(){}},fetch:async url=>{requests.push(url);return{ok:!(failVocabulary&&url.includes('article-vocabulary')),text:async()=>(files.get(url)??fs.readFileSync(path.join(root,url),'utf8'))+(tamper&&url==='materials/articles/index.json'?' ':'')}}};ctx.window={QuizUI:{registerItems:items=>registered.push(...items),getStore:()=>({bookmarks,logs:[]})},AppUI:{addCatalog:items=>saved.push(...items)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'material-catalog.js'),'utf8'),ctx);await ctx.window.MaterialCatalog.ready;return{api:ctx.window.MaterialCatalog,registered,saved,unit,requests,articles,setTamper:value=>{tamper=value}};}
test('initial catalog loads metadata and units without article bodies or vocabulary',async()=>{const {api,registered,unit,requests}=await load();assert.ok(api.articles().length>=3);assert.equal(api.units().length,30);assert.equal(api.items().length,300);assert.equal(registered.length,300);assert.equal(unit.items.length,10);assert.ok(!requests.some(x=>/articles\/(?!index)/.test(x)||x.includes('article-vocabulary')));assert.ok(api.articles().every(x=>!x.paragraphs&&!x.vocabulary&&!x.comprehension));assert.equal(api.visible({publishedAt:'2099-01-01T00:00:00Z'}),false);});
test('opening one article loads only that body and sidecar, concurrent requests are deduplicated',async()=>{const {api,requests,articles}=await load();const id=articles[0].a.id;const [a,b]=await Promise.all([api.getArticle(id),api.getArticle(id)]);assert.equal(a,b);assert.equal(a.vocabulary.length,5);assert.equal(api.items().length,305);assert.equal(requests.filter(x=>x===articles[0].ref.path).length,1);assert.equal(requests.filter(x=>x===articles[0].a.id).length,0);assert.ok(api.items().filter(x=>x.sourceKind==='article').every(x=>x.context&&x.articleId===id));});
test('stored article word IDs hydrate vocabulary without loading article body',async()=>{const preliminary=await load();const id=preliminary.articles[0].a.vocabulary[0].id;const {api,requests}=await load({bookmarks:[id]});await api.hydrateSaved();assert.ok(api.items().some(x=>x.id===id));assert.ok(!requests.some(x=>/articles\/(?!index)/.test(x)));});
test('an unknown requested word fails explicitly rather than being silently dropped',async()=>{const {api}=await load();await assert.rejects(api.getWords(['missing-word']),/取得できません/);});
test('a JSON edit without revalidation is not imported',async()=>{const {api,registered,saved}=await load({tamper:true});assert.equal(api.articles().length,0);assert.equal(registered.length,0);assert.equal(saved.length,0);assert.ok(api.error());});

test('failed saved-word hydration ends pending state, preserves IDs, and reports an error',async()=>{const preliminary=await load();const id=preliminary.articles[0].a.vocabulary[0].id;const bookmarks=[id];const {api}=await load({bookmarks,failVocabulary:true});await api.hydrateSaved();assert.equal(api.hydrating(),false);assert.ok(api.error());assert.equal(bookmarks[0],id);});

test('an initial index hash failure remains an error after hydration, even with no saved IDs',async()=>{const {api}=await load({tamper:true});const initial=api.error();assert.ok(initial);await api.hydrateSaved();assert.ok(api.error());assert.equal(api.articles().length,0);assert.equal(api.hydrating(),false);await assert.rejects(api.getWords([]),/検証/);});
test('manual hydration retry re-fetches initialization and can recover after a repaired index',async()=>{const {api,setTamper,requests}=await load({tamper:true});assert.ok(api.error());setTamper(false);await api.hydrateSaved();assert.equal(api.error(),null);assert.equal(api.hydrating(),false);assert.ok(api.articles().length>=3);assert.equal(requests.filter(x=>x==='materials/manifest.json').length,2);});
