const test = require('node:test');
const assert = require('node:assert/strict');
const {createSyncClient} = require('../supabase-sync.js');
const memory = () => { const values=new Map(); return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)}; };
function storage(){let uid=null,pending=[],cursors={};const rows={};return {getUser:()=>uid,setUser:id=>uid=id,pending:()=>pending,acknowledge:(table,key,rev)=>{pending=pending.filter(p=>!(p.table===table&&p.key===key&&p.revision===rev));},merge:(table,r)=>{rows[table]=r;},cursor:(t,v)=>v===undefined?cursors[t]:(cursors[t]=v),subscribe:()=>()=>{},migrationPreview:()=>({available:false,counts:{}}),exportData:()=>({learningData:{},pendingData:pending}),getItem:()=>null,setItem:()=>{},enqueue:p=>pending.push(p),rows};}
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body});
async function client(store,rest,extra={}){const c=createSyncClient({fetch:async(url,opts)=>{if(url.includes('config/supabase'))return response({url:'https://unit.supabase.co',anonKey:'public-test'});if(url.includes('sync-policy'))return response({deltaOverlapMs:600000});if(url.includes('/token'))return response({access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,user:{id:'user-a',email:'learner@example.invalid'}});return rest(url,opts);},authStorage:memory(),online:()=>true,pageSize:2,...extra});await c.init({storage:store});return c;}
test('missing config leaves learning storage untouched and disables sync',async()=>{const s=storage();const c=createSyncClient({fetch:async()=>response({},404),authStorage:memory()});await c.init({storage:s});assert.equal(c.getState().enabled,false);assert.equal(s.getUser(),null);});
test('failed send remains pending and successful retry uses ignore duplicates for append logs',async()=>{const s=storage();let failing=false,prefer;const c=await client(s,(url,o)=>{if(o.method==='POST'){prefer=o.headers.Prefer;if(failing)return response({},503);return response([JSON.parse(o.body)]);}return response([]);});await c.login('x','secret');s.enqueue({table:'answer_logs',key:'event',revision:'r1',row:{event_id:'event',user_id:'user-a'}});failing=true;await c.sync();assert.equal(s.pending().length,1);assert.equal(c.getState().status,'failed');failing=false;await c.sync();assert.equal(s.pending().length,0);assert.match(prefer,/ignore-duplicates/);});
test('stale mutable write reads back accepted server row before acknowledgement',async()=>{const s=storage();let readback=false;const server={user_id:'user-a',setting_key:'mode',value:'en',updated_at:'2026-10-05T12:00:00Z',server_updated_at:'2026-10-05T13:00:00Z'};const c=await client(s,(url,o)=>{if(o.method==='POST')return response([]);if(url.includes('setting_key=eq.')){readback=true;return response([server]);}return response(url.includes('/preferences')?[server]:[]);});await c.login('x','secret');s.enqueue({table:'preferences',key:'mode',revision:'old',row:{...server,value:'ja',updated_at:'2026-10-04T00:00:00Z'}});await c.sync();assert.equal(readback,true);assert.equal(s.pending().length,0);assert.equal(s.rows.preferences[0].value,'en');});
test('table cursor uses server time overlap and advances only after complete pull',async()=>{const s=storage();const urls=[];const c=await client(s,(url)=>{urls.push(url);return response([]);});await c.login('x','secret');s.cursor('answer_logs','2026-10-05T12:00:00.000Z');await c.sync();const url=new URL(urls.filter(u=>u.includes('/answer_logs')).at(-1));assert.equal(url.searchParams.get('server_updated_at'),'gte.2026-10-05T11:50:00.000Z');});
test('success acknowledges only the sent revision when edited during request',async()=>{const s=storage();let release,blocked=false;const c=await client(s,async(url,o)=>{if(o.method==='POST'&&!blocked){blocked=true;await new Promise(r=>release=r);return response([JSON.parse(o.body)]);}return response([]);});await c.login('x','secret');const row={user_id:'user-a',setting_key:'mode',value:'ja'};s.enqueue({table:'preferences',key:'mode',revision:'r1',row});const syncing=c.sync();while(!release)await new Promise(r=>setImmediate(r));s.enqueue({table:'preferences',key:'mode',revision:'r2',row:{...row,value:'en'}});release();await syncing;assert.equal(s.pending().length,1);assert.equal(s.pending()[0].revision,'r2');});
test('response for logged out user cannot modify guest namespace',async()=>{const s=storage();let release,block=false;const c=await client(s,async(url,o)=>{if(url.includes('/answer_logs')&&block){await new Promise(r=>release=r);return response([{user_id:'user-a',event_id:'old',server_updated_at:'2026-10-05T10:00:00Z'}]);}return response([]);});await c.login('x','secret');block=true;const syncing=c.sync();while(!release)await new Promise(r=>setImmediate(r));await c.logout();s.rows.answer_logs=[];release();await syncing;assert.deepEqual(s.rows.answer_logs,[]);assert.equal(c.getState().user,null);});
test('keyset pagination handles equal server times and does not use offset',async()=>{const s=storage();let active=false,calls=0;const rows=['a','b','c'].map(event_id=>({user_id:'user-a',event_id,server_updated_at:'2026-10-05T10:00:00Z'}));const c=await client(s,(url)=>{const query=new URL(url).searchParams;if(active&&url.includes('/answer_logs')){calls++;assert.equal(query.has('offset'),false);if(calls===1)return response(rows.slice(0,2));assert.match(query.get('or'),/event_id\.gt\."b"/);return response(rows.slice(2));}return response([]);});await c.login('x','secret');active=true;await c.sync();assert.equal(calls,2);assert.equal(s.rows.answer_logs.length,3);assert.equal(s.cursor('answer_logs'),rows[0].server_updated_at);});
test('failed later page keeps previous table cursor and does not merge partial rows',async()=>{const s=storage();let active=false,calls=0;const c=await client(s,(url)=>{if(active&&url.includes('/answer_logs')){if(++calls===1)return response(['a','b'].map(event_id=>({user_id:'user-a',event_id,server_updated_at:'2026-10-05T12:00:00Z'})));return response({},503);}return response([]);});await c.login('x','secret');s.cursor('answer_logs','2026-10-05T10:00:00Z');active=true;await c.sync();assert.equal(s.cursor('answer_logs'),'2026-10-05T10:00:00Z');assert.deepEqual(s.rows.answer_logs,[]);assert.equal(c.getState().status,'failed');});
test('manual resync omits delta filters on every table',async()=>{const s=storage(),urls=[];const c=await client(s,url=>{urls.push(url);return response([]);});await c.login('x','secret');s.cursor('preferences','2026-10-05T12:00:00Z');urls.length=0;await c.resync();assert.equal(urls.length,6);assert.ok(urls.every(url=>!new URL(url).searchParams.has('server_updated_at')));});
test('guest import downloads backup before importing and confirms target IDs only',async()=>{const s=storage(),steps=[],row={user_id:'user-a',word_key:'retention'};s.migrationPreview=()=>({available:true,counts:{saved_words:1},guestCounts:{saved_words:1},legacyCounts:{saved_words:0}});s.importGuest=()=>{steps.push('import');return {snapshotId:'s1',targetRows:{saved_words:[row]}};};s.markGuestImported=(id,uid)=>steps.push('verified:'+id+':'+uid);const c=await client(s,url=>response(url.includes('word_key=eq.')?[row]:[]),{download:()=>steps.push('backup')});await c.login('x','secret');const result=await c.importGuest();assert.deepEqual(steps,['backup','import','verified:s1:user-a']);assert.equal(result.success,true);assert.equal(result.targetCounts.saved_words,1);});
test('unmatched imported ID is a failure and never marks migration complete',async()=>{const s=storage();let marked=false;s.migrationPreview=()=>({available:true,counts:{saved_words:1}});s.importGuest=()=>({snapshotId:'s1',targetRows:{saved_words:[{user_id:'user-a',word_key:'missing'}]}});s.markGuestImported=()=>marked=true;const c=await client(s,()=>response([]));await c.login('x','secret');await assert.rejects(c.importGuest(),/件数/);assert.equal(marked,false);assert.equal(c.getState().status,'failed');assert.equal(c.getState().migrationResult,null);});
test('namespace write failure during login cannot fetch user rows into guest storage',async()=>{const s=storage();let restCalls=0;const switchUser=s.setUser;s.setUser=uid=>{if(uid==='user-a')throw new Error('Quota exceeded');switchUser(uid);};const c=await client(s,()=>{restCalls++;return response([]);});await assert.rejects(c.login('x','secret'),/保存領域/);await c.sync();assert.equal(restCalls,0);assert.equal(s.getUser(),null);assert.equal(c.getState().user,null);});
test('auth persistence failure rolls back the namespace before any sync',async()=>{const s=storage();let restCalls=0;const auth=memory();auth.setItem=()=>{throw new Error('Quota exceeded');};const c=await client(s,()=>{restCalls++;return response([]);},{authStorage:auth});await assert.rejects(c.login('x','secret'),/保存領域/);assert.equal(s.getUser(),null);assert.equal(c.getState().user,null);assert.equal(restCalls,0);});
test('storage ownership mismatch stops every network synchronization request',async()=>{const s=storage();let restCalls=0;const c=await client(s,()=>{restCalls++;return response([]);});await c.login('x','secret');restCalls=0;s.setUser(null);await c.sync();assert.equal(restCalls,0);assert.equal(c.getState().status,'failed');});
test('failed logout namespace switch clears auth and stops sync without writing guest data',async()=>{const s=storage();let restCalls=0;const auth=memory(),c=await client(s,()=>{restCalls++;return response([]);},{authStorage:auth});await c.login('x','secret');const switchUser=s.setUser;s.setUser=uid=>{if(uid===null)throw new Error('Storage inaccessible');switchUser(uid);};restCalls=0;await c.logout();await c.sync();assert.equal(c.getState().user,null);assert.equal(c.getState().status,'failed');assert.equal(auth.getItem('english-notes.auth.session.v1'),null);assert.equal(s.getUser(),'user-a');assert.equal(restCalls,0);});
test('startup namespace failure disables synchronization rather than restoring authenticated UI',async()=>{const s=storage(),auth=memory();auth.setItem('english-notes.auth.session.v1',JSON.stringify({user:{id:'user-a',email:'learner@example.invalid'},access_token:'test-token',refresh_token:'test-refresh',expires_at:Date.now()/1000+3600}));s.setUser=()=>{throw new Error('Quota exceeded');};let restCalls=0;const c=await client(s,()=>{restCalls++;return response([]);},{authStorage:auth});assert.equal(c.getState().enabled,false);assert.equal(c.getState().user,null);assert.equal(s.getUser(),null);assert.equal(restCalls,0);});
test('login preserves safe auth error classification without exposing server message',async()=>{
 for(const [status,code] of [[400,'invalid_credentials'],[503,'unexpected_failure']]){
  const s=storage();const c=await client(s,()=>response([]),{fetch:async url=>{
   if(url.includes('config/supabase'))return response({url:'https://unit.supabase.co',anonKey:'public-test'});
   if(url.includes('sync-policy'))return response({deltaOverlapMs:600000});
   return response({code,message:'PRIVATE RAW SERVER MESSAGE'},status);
  }});
  await assert.rejects(c.login('x','secret'),error=>error.status===status&&error.code===code&&!error.message.includes('PRIVATE'));
  assert.equal(s.getUser(),null);
 }
});
test('network login failure carries connection classification and leaves guest data unchanged',async()=>{
 const s=storage();const c=await client(s,()=>response([]),{fetch:async url=>{
  if(url.includes('config/supabase'))return response({url:'https://unit.supabase.co',anonKey:'public-test'});
  if(url.includes('sync-policy'))return response({deltaOverlapMs:600000});
  throw new TypeError('Failed to fetch');
 }});
 await assert.rejects(c.login('x','secret'),error=>error.code==='connection_failed');
 assert.equal(s.getUser(),null);
});
test('server rejection without an auth code is classified as connection failure',async()=>{
 const c=await client(storage(),()=>response([]),{fetch:async url=>{
  if(url.includes('config/supabase'))return response({url:'https://unit.supabase.co',anonKey:'public-test'});
  if(url.includes('sync-policy'))return response({deltaOverlapMs:600000});
  return response({},503);
 }});
 await assert.rejects(c.login('x','secret'),error=>error.status===503&&error.code==='connection_failed');
});
